"""Document blobs in PostgreSQL: compression, storage, and the round trip.

The claim under test is narrow and absolute: **what comes out is byte-identical to what went
in.** Everything else here supports that. A document is the evidence behind a posted ledger
entry, and ``document.sha256`` - the digest of the original upload - is simultaneously the
duplicate key, the storage address, and the integrity check applied on download. A round trip
that returned an equivalent-but-different file would fail all three at once, so "close enough"
is not a category that exists in this module.

The compression tests are pure and need nothing running. The store and HTTP tests need
PostgreSQL and are marked ``integration``.
"""

from __future__ import annotations

import io
import random
import uuid
import zlib
from typing import TYPE_CHECKING

import pytest
from httpx import AsyncClient
from pydantic import SecretStr
from sqlalchemy import func, select

from app.core.config import settings
from app.modules.ocr.compression import (
    MIN_SAVING_RATIO,
    MIN_WORTH_TRYING,
    Codec,
    DecompressionError,
    compress,
    compress_sync,
    decompress,
    decompress_sync,
)
from app.modules.ocr.engines import DocumentFormat
from app.modules.ocr.models import DocumentBlob
from app.modules.ocr.storage import (
    BlobCorruptedError,
    BlobMissingError,
    DatabaseDocumentStore,
    relative_path_for,
    sha256_of,
)
from tests.test_ocr_engines import _write_simple_pdf

if TYPE_CHECKING:
    from collections.abc import Iterator

    from sqlalchemy.ext.asyncio import AsyncSession

    from app.modules.organizations.models import Organization


# =============================================================================
# Fixtures and sample documents
# =============================================================================
@pytest.fixture(autouse=True)
def database_backed_storage() -> Iterator[None]:
    """Force the database backend, whatever the developer's ``.env`` says.

    ``document_storage`` is derived from whether object-storage credentials are configured, so
    a machine that has them would otherwise send every fixture document to a real bucket -
    and these tests assert on the contents of ``document_blob``, which would then be empty.
    """
    original = settings.minio_secret_key
    settings.minio_secret_key = SecretStr("")
    assert settings.document_storage == "database"
    try:
        yield
    finally:
        settings.minio_secret_key = original


def text_pdf(lines: int = 400) -> bytes:
    """A digital PDF with a text layer - the best case for compression.

    Deliberately repetitive: this stands in for an invoice generated by accounting software,
    which is what most uploads to this system actually are.
    """
    buffer = io.BytesIO()
    _write_simple_pdf(
        buffer,
        "\n".join(
            f"INVOICE LINE {index:04d}  QTY 10  RATE 1500.00  AMOUNT 15000.00"
            for index in range(lines)
        ),
    )
    return buffer.getvalue()


def incompressible(size: int = 200_000) -> bytes:
    """Bytes with no structure left to exploit.

    Stands in for a scanned PDF or a JPEG, whose image streams are already entropy-coded.

    Seeded rather than ``os.urandom`` so a failure is reproducible, and genuinely random
    rather than an arithmetic pattern: the first version of this generated bytes from
    ``(index * 7919 + ...) % 251``, which *looks* like noise and which zlib compressed by 30%
    - so the test asserting "incompressible input is stored verbatim" failed against a
    perfectly correct codec. A pattern a human cannot see is not a pattern zlib cannot see.
    """
    # S311 (not a CSPRNG) is the point, not an oversight: this needs bytes that are
    # reproducible across runs, which `secrets` deliberately cannot provide. Nothing here is
    # a credential - it is filler chosen to have no structure for zlib to find.
    return random.Random(20260805).randbytes(size)  # noqa: S311


class Meta:
    """Minimal ``BlobMetadata``."""

    def __init__(self, filename: str = "invoice.pdf", mime: str = "application/pdf") -> None:
        self.original_filename = filename
        self.mime_type = mime
        self.uploaded_by_user_id = None


@pytest.fixture
def store(db: AsyncSession, organization: Organization) -> DatabaseDocumentStore:
    return DatabaseDocumentStore(db, organization.id)


def key_for(organization: Organization, data: bytes) -> str:
    return relative_path_for(organization.id, sha256_of(data), DocumentFormat.PDF)


# =============================================================================
# Compression - pure
# =============================================================================
class TestCompressionRoundTrip:
    """The property everything else depends on."""

    # `pytest.param(..., id=...)` rather than a bare list, and the id is load-bearing on
    # Windows: pytest derives the node id from the parameter's repr and exports it as
    # PYTEST_CURRENT_TEST, where a 200 KB payload trips the 32767-character limit on an
    # environment variable and every case in this class errors out before it runs.
    @pytest.mark.parametrize(
        "payload",
        [
            pytest.param(b"", id="empty"),
            pytest.param(b"\x00", id="one-byte"),
            pytest.param(b"%PDF-1.7\n", id="tiny"),
            pytest.param(b"A" * 100_000, id="highly-compressible"),
            pytest.param(text_pdf(), id="text-pdf"),
            pytest.param(incompressible(), id="incompressible"),
            pytest.param(bytes(range(256)) * 500, id="all-byte-values"),
            pytest.param(b"\x00" * 50_000, id="null-bytes"),
        ],
    )
    def test_byte_identical(self, payload: bytes) -> None:
        result = compress_sync(payload)
        assert decompress_sync(result.codec, result.payload) == payload

    def test_digest_survives_the_round_trip(self) -> None:
        """The check that actually runs on every download.

        `document.sha256` covers the *original* bytes, so a codec that rewrote anything would
        make every download raise `BlobCorruptedError`.
        """
        original = text_pdf()
        digest = sha256_of(original)

        result = compress_sync(original)
        assert sha256_of(decompress_sync(result.codec, result.payload)) == digest

    async def test_async_wrappers_agree_with_the_sync_ones(self) -> None:
        payload = text_pdf()
        result = await compress(payload)
        assert await decompress(result.codec, result.payload) == payload


class TestCompressionDecisions:
    """When compressing is worth it, and when storing verbatim is the right answer."""

    def test_a_text_pdf_compresses_substantially(self) -> None:
        result = compress_sync(text_pdf())
        assert result.codec is Codec.ZLIB
        # The fixture is repetitive invoice lines, so this is the good case. Asserted as a
        # floor rather than a range: a future codec change may beat it and must not fail here.
        assert result.saving_ratio > 0.5, f"only saved {result.saving_ratio:.1%}"

    def test_incompressible_input_is_stored_verbatim(self) -> None:
        """A scan or a JPEG has nothing left to give, and that is not a failure.

        Storing a 0.1%-smaller payload would cost a full decompression pass on every download
        of it, forever - so the codec has to be allowed to decline.
        """
        payload = incompressible()
        result = compress_sync(payload)
        assert result.codec is Codec.NONE
        assert result.payload is payload
        assert result.stored_size == len(payload)

    def test_marginal_gains_are_declined(self) -> None:
        """A saving under the floor is not worth the read-side price.

        Constructed rather than found: mostly-random bytes with a small compressible tail, so
        zlib finds *something* but not enough. Asserting the premise first means a future
        codec change makes this test say "the fixture is no longer marginal" instead of
        silently testing nothing.
        """
        payload = incompressible(100_000) + b"A" * 2_000
        gained = 1 - len(zlib.compress(payload, level=6)) / len(payload)
        assert 0 < gained < MIN_SAVING_RATIO, f"fixture gained {gained:.2%} - adjust it"
        assert compress_sync(payload).codec is Codec.NONE

    def test_tiny_input_is_not_even_attempted(self) -> None:
        payload = b"%PDF-1.4 tiny"
        assert len(payload) < MIN_WORTH_TRYING
        assert compress_sync(payload).codec is Codec.NONE

    def test_sizes_and_ratio_are_reported(self) -> None:
        payload = text_pdf()
        result = compress_sync(payload)
        assert result.original_size == len(payload)
        assert result.stored_size == len(result.payload)
        assert result.saving_ratio == pytest.approx(1 - result.stored_size / result.original_size)

    def test_empty_input_has_a_defined_ratio(self) -> None:
        """Guards a division by zero on a degenerate but reachable input."""
        assert compress_sync(b"").saving_ratio == 0.0


class TestDecompressionFailures:
    def test_corrupt_payload_raises(self) -> None:
        result = compress_sync(text_pdf())
        assert result.codec is Codec.ZLIB
        with pytest.raises(DecompressionError):
            decompress_sync(Codec.ZLIB, result.payload[:-40] + b"garbage")

    def test_unknown_codec_is_a_clear_error(self) -> None:
        """A blob written by a newer version must say so, not raise a bare ValueError."""
        with pytest.raises(DecompressionError, match="Unknown compression codec"):
            decompress_sync("brotli-9", b"whatever")

    def test_codec_accepted_as_a_plain_string(self) -> None:
        """It arrives from a database column, which yields a str under some drivers."""
        result = compress_sync(text_pdf())
        assert decompress_sync(str(result.codec), result.payload) == text_pdf()


# =============================================================================
# The store
# =============================================================================
@pytest.mark.integration
class TestDatabaseDocumentStore:
    async def test_write_then_read_is_byte_identical(
        self, store: DatabaseDocumentStore, organization: Organization
    ) -> None:
        payload = text_pdf()
        key = key_for(organization, payload)

        await store.write(key, payload, Meta())
        assert await store.read(key) == payload

    async def test_read_verifies_against_the_digest(
        self, store: DatabaseDocumentStore, organization: Organization
    ) -> None:
        payload = text_pdf()
        key = key_for(organization, payload)
        await store.write(key, payload, Meta())

        assert await store.read(key, verify=sha256_of(payload)) == payload

        with pytest.raises(BlobCorruptedError):
            await store.read(key, verify="0" * 64)

    async def test_bytes_are_stored_compressed(
        self, db: AsyncSession, store: DatabaseDocumentStore, organization: Organization
    ) -> None:
        """The database must hold the compressed form, not the original.

        Asserted on the column rather than through the store, because reading through the
        store decompresses - which is exactly what would hide a backend that quietly stored
        the raw upload.
        """
        payload = text_pdf()
        key = key_for(organization, payload)
        await store.write(key, payload, Meta())

        blob = (
            await db.execute(select(DocumentBlob).where(DocumentBlob.storage_key == key))
        ).scalar_one()

        assert blob.compression is Codec.ZLIB
        assert blob.data != payload
        assert blob.compressed_size < blob.original_size
        assert blob.original_size == len(payload)
        assert blob.compressed_size == len(blob.data)
        assert zlib.decompress(blob.data) == payload

    async def test_metadata_is_recorded(
        self, db: AsyncSession, store: DatabaseDocumentStore, organization: Organization
    ) -> None:
        payload = text_pdf()
        key = key_for(organization, payload)
        await store.write(key, payload, Meta(filename="supplier bill.pdf"))

        blob = (
            await db.execute(select(DocumentBlob).where(DocumentBlob.storage_key == key))
        ).scalar_one()

        assert blob.original_filename == "supplier bill.pdf"
        assert blob.mime_type == "application/pdf"
        assert blob.sha256 == sha256_of(payload)
        assert blob.organization_id == organization.id
        assert blob.uploaded_at is not None

    async def test_writing_the_same_key_twice_stores_one_row(
        self, db: AsyncSession, store: DatabaseDocumentStore, organization: Organization
    ) -> None:
        """Content-addressed, so a second write of the same bytes is a no-op."""
        payload = text_pdf()
        key = key_for(organization, payload)

        await store.write(key, payload, Meta())
        await store.write(key, payload, Meta())

        count = (
            await db.execute(
                select(func.count())
                .select_from(DocumentBlob)
                .where(DocumentBlob.storage_key == key)
            )
        ).scalar_one()
        assert count == 1

    async def test_missing_blob_is_410_not_404(self, store: DatabaseDocumentStore) -> None:
        """The reference is valid and the content is gone - a different thing from a typo."""
        with pytest.raises(BlobMissingError) as caught:
            await store.read("nonexistent/aa/deadbeef.pdf")
        assert caught.value.status_code == 410

    async def test_exists(self, store: DatabaseDocumentStore, organization: Organization) -> None:
        payload = text_pdf()
        key = key_for(organization, payload)

        assert not await store.exists(key)
        await store.write(key, payload, Meta())
        assert await store.exists(key)

    async def test_delete_removes_the_row(
        self, db: AsyncSession, store: DatabaseDocumentStore, organization: Organization
    ) -> None:
        payload = text_pdf()
        key = key_for(organization, payload)
        await store.write(key, payload, Meta())

        await store.delete(key)

        assert not await store.exists(key)
        with pytest.raises(BlobMissingError):
            await store.read(key)

    async def test_deleting_something_absent_is_not_an_error(
        self, store: DatabaseDocumentStore
    ) -> None:
        await store.delete("nothing/aa/here.pdf")

    async def test_incompressible_input_round_trips_through_the_store(
        self, db: AsyncSession, store: DatabaseDocumentStore, organization: Organization
    ) -> None:
        """The Codec.NONE path has to work end to end, not just in the codec."""
        payload = incompressible()
        key = relative_path_for(organization.id, sha256_of(payload), DocumentFormat.JPEG)

        await store.write(key, payload, Meta(filename="scan.jpg", mime="image/jpeg"))

        blob = (
            await db.execute(select(DocumentBlob).where(DocumentBlob.storage_key == key))
        ).scalar_one()
        assert blob.compression is Codec.NONE
        assert blob.compressed_size == blob.original_size
        assert await store.read(key, verify=sha256_of(payload)) == payload

    async def test_a_tenant_cannot_read_another_tenants_blob(
        self, db: AsyncSession, organization: Organization
    ) -> None:
        """Isolation is a SQL predicate, not a convention about key prefixes.

        The key embeds the organization id, so a store that filtered only by key would appear
        to work. This asserts the `WHERE organization_id = ...` is really there, by asking a
        store scoped to a different tenant for a key it can name exactly.
        """
        payload = text_pdf()
        key = key_for(organization, payload)
        await DatabaseDocumentStore(db, organization.id).write(key, payload, Meta())

        intruder = DatabaseDocumentStore(db, uuid.uuid4())
        assert not await intruder.exists(key)
        with pytest.raises(BlobMissingError):
            await intruder.read(key)


# =============================================================================
# Over HTTP - the flow the frontend actually uses
# =============================================================================
@pytest.mark.integration
class TestUploadDownloadIntegrity:
    """The requirement in one place: the file downloaded is the file uploaded.

    Uses the real endpoints, so this covers the router, the service, the compression, the
    ``BYTEA`` column, the decompression, and the digest verification in one pass. Reuses the
    fixtures from ``test_ocr_api`` rather than rebuilding an organization with document
    permissions, because that setup is substantial and duplicating it would let the two drift.
    """

    async def test_downloaded_bytes_are_identical_to_the_upload(
        self, authed_client: AsyncClient, api: str
    ) -> None:
        from tests.test_ocr_api import invoice_pdf, upload

        original = invoice_pdf()
        document = (await upload(authed_client, api, original))["document"]

        response = await authed_client.get(f"{api}/documents/{document['id']}/file")

        assert response.status_code == 200
        assert response.content == original
        assert sha256_of(response.content) == document["sha256"]

    async def test_a_large_document_round_trips(self, authed_client: AsyncClient, api: str) -> None:
        """Multi-megabyte, so the payload is well past any single-chunk path."""
        from tests.test_ocr_api import upload

        original = text_pdf(lines=20_000)
        assert len(original) > 1_000_000

        document = (await upload(authed_client, api, original))["document"]
        response = await authed_client.get(f"{api}/documents/{document['id']}/file")

        assert response.status_code == 200
        assert response.content == original

    async def test_the_stored_row_is_smaller_than_the_upload(
        self, db: AsyncSession, authed_client: AsyncClient, api: str
    ) -> None:
        """Compression is actually happening on the request path, not only in unit tests."""
        from tests.test_ocr_api import upload

        original = text_pdf(lines=2_000)
        document = (await upload(authed_client, api, original))["document"]

        blob = (
            await db.execute(select(DocumentBlob).where(DocumentBlob.sha256 == document["sha256"]))
        ).scalar_one()

        assert blob.compression is Codec.ZLIB
        assert blob.compressed_size < len(original)
        assert blob.original_size == len(original)

    async def test_an_image_upload_round_trips(self, authed_client: AsyncClient, api: str) -> None:
        """A PNG is already compressed, so this is the Codec.NONE path over HTTP."""
        from tests.test_ocr_api import upload

        try:
            from PIL import Image
        except ImportError:  # pragma: no cover - Pillow arrives via qrcode[pil]
            pytest.skip("Pillow is not installed")

        buffer = io.BytesIO()
        Image.new("RGB", (400, 300), (240, 240, 240)).save(buffer, format="PNG")
        original = buffer.getvalue()

        document = (await upload(authed_client, api, original, filename="scan.png"))["document"]
        response = await authed_client.get(f"{api}/documents/{document['id']}/file")

        assert response.status_code == 200
        assert response.content == original

    async def test_the_blob_is_gone_after_a_rolled_back_upload(
        self, db: AsyncSession, organization: Organization
    ) -> None:
        """The reason blobs belong in the database rather than beside it.

        A write to a filesystem or a bucket is not in the transaction, so a request that
        failed after storing bytes leaked them permanently - orphans nobody would ever look
        for. Here the blob is in the same transaction as everything else, so it goes when the
        transaction goes. Demonstrated with a savepoint, which is what the request-scoped
        session actually uses.
        """
        payload = text_pdf()
        key = key_for(organization, payload)
        store = DatabaseDocumentStore(db, organization.id)

        savepoint = await db.begin_nested()
        await store.write(key, payload, Meta())
        assert await store.exists(key)
        await savepoint.rollback()

        assert not await store.exists(key)
