"""OCR engines - turning an uploaded file into text.

**A digital PDF is not an OCR problem.** Most GST invoices arrive by email as PDFs
generated by the supplier's accounting software, and those carry an exact text
layer. Reading it is instant, free, and character-perfect; rasterising the page and
running OCR over the picture can only be worse. So the text layer is tried first and
recognition is the fallback, not the default. This is the single largest accuracy win
in the pipeline and it costs nothing.

**Tesseract, not PaddleOCR or EasyOCR.** The deep-learning engines are more accurate
on hard photographs, and they pull 500 MB to 2 GB of wheels to get there. This product
is meant to be operated by one person on a small VPS, so a 30 MB system binary that
reads a GST invoice well is the right trade. The extra also stays optional: the app
boots and runs without it, with document upload reporting itself unavailable rather
than crashing at import.

**Availability is probed, never assumed.** ``pip install pytesseract`` installs a
*wrapper* around a binary it does not ship. Treating the import as proof the engine
works is how this fails in production with a ``TesseractNotFoundError`` from inside a
request handler.

**Recognition runs in a worker thread.** Tesseract is a blocking, CPU-bound
subprocess that takes seconds on a full page. Calling it directly from a coroutine
would stall the event loop for every other request in the process - on a
single-worker deployment, which is the target, that means the whole application
freezes while one invoice is scanned.
"""

from __future__ import annotations

import io
from dataclasses import dataclass
from decimal import Decimal
from enum import StrEnum
from typing import Any, Final, Protocol, runtime_checkable

import anyio.to_thread

from app.core.config import settings
from app.core.exceptions import AppError, BusinessRuleError, ValidationError
from app.core.logging import get_logger

log = get_logger(__name__)


# ---------------------------------------------------------------------------
# Formats
# ---------------------------------------------------------------------------
class DocumentFormat(StrEnum):
    """An accepted upload format, named by its MIME type."""

    PDF = "application/pdf"
    PNG = "image/png"
    JPEG = "image/jpeg"
    TIFF = "image/tiff"
    WEBP = "image/webp"

    @property
    def is_image(self) -> bool:
        return self is not DocumentFormat.PDF

    @property
    def extension(self) -> str:
        return {
            DocumentFormat.PDF: "pdf",
            DocumentFormat.PNG: "png",
            DocumentFormat.JPEG: "jpg",
            DocumentFormat.TIFF: "tif",
            DocumentFormat.WEBP: "webp",
        }[self]


#: Magic-byte signatures, longest-first so TIFF's 4-byte prefix cannot shadow a
#: longer match.
_SIGNATURES: Final[tuple[tuple[bytes, DocumentFormat], ...]] = (
    (b"\x89PNG\r\n\x1a\n", DocumentFormat.PNG),
    (b"%PDF-", DocumentFormat.PDF),
    (b"\xff\xd8\xff", DocumentFormat.JPEG),
    (b"II*\x00", DocumentFormat.TIFF),
    (b"MM\x00*", DocumentFormat.TIFF),
)


def sniff_format(data: bytes) -> DocumentFormat | None:
    """Identify a format from its leading bytes.

    **The client's declared content type is not consulted.** A browser sends
    whatever the OS guessed from the file extension, and an attacker sends whatever
    they like - so a file named ``invoice.pdf`` announcing ``application/pdf`` can
    be an HTML document that executes script the moment it is served back. Deciding
    from the actual bytes is the only check that means anything.

    Returning ``None`` rather than raising keeps this usable as a predicate; the
    caller decides what an unrecognised upload means.
    """
    for signature, fmt in _SIGNATURES:
        if data.startswith(signature):
            return fmt

    # WebP is a RIFF container: "RIFF" <4-byte size> "WEBP".
    if data[:4] == b"RIFF" and data[8:12] == b"WEBP":
        return DocumentFormat.WEBP

    return None


# ---------------------------------------------------------------------------
# Failures
# ---------------------------------------------------------------------------
class UnsupportedDocumentError(ValidationError):
    code = "unsupported_document"
    message = "That file type cannot be read. Upload a PDF, PNG, JPEG, TIFF, or WebP."


class DocumentTooLargeError(ValidationError):
    code = "document_too_large"
    message = "That file is too large."


class EngineUnavailableError(AppError):
    """No engine can handle the format on this deployment.

    Deliberately a 501 rather than a 503: 503 says "try again shortly", but a
    missing Tesseract install will still be missing on retry. The fix is an
    operator action, and the status code should say so.
    """

    status_code = 501
    code = "ocr_unavailable"
    message = "Text recognition is not available on this server."


class NoTextRecognisedError(BusinessRuleError):
    code = "no_text_recognised"
    message = "No readable text was found in that document."


class ScannedPdfError(BusinessRuleError):
    """A PDF with no text layer.

    Rasterising it would need Poppler plus ``pdf2image``, a system dependency
    deliberately not taken on. Saying so plainly beats returning an empty
    extraction that looks like a failed parse - the user can re-upload a photo or
    a PNG export and get a result immediately.
    """

    code = "pdf_has_no_text_layer"
    message = (
        "That PDF is a scan with no text layer. Upload it as an image "
        "(PNG or JPEG) instead and it will be read."
    )


# ---------------------------------------------------------------------------
# Result
# ---------------------------------------------------------------------------
@dataclass(frozen=True, slots=True)
class OcrResult:
    """Recognised text plus how much to trust it."""

    text: str
    engine: str
    #: Mean per-word confidence, 0-1. ``None`` when the engine does not report one.
    mean_confidence: Decimal | None
    page_count: int
    #: True when the characters were read from the file rather than recognised from
    #: pixels. Exact, so field confidence is not discounted for legibility.
    is_exact: bool = False

    @property
    def is_empty(self) -> bool:
        return not self.text.strip()


# ---------------------------------------------------------------------------
# Engine protocol
# ---------------------------------------------------------------------------
@runtime_checkable
class OcrEngine(Protocol):
    """What an engine must provide.

    A ``Protocol`` rather than an abstract base class: engines are adapters around
    third-party code, and structural typing means a new one can be dropped in - or
    a fake substituted in tests - without importing anything from here. The
    recognition call is **synchronous** by design; the async wrapper below owns
    thread offloading so no engine has to think about it.
    """

    name: str

    def supports(self, fmt: DocumentFormat) -> bool: ...

    def is_available(self) -> bool: ...

    def recognise(self, data: bytes, fmt: DocumentFormat) -> OcrResult: ...


# ---------------------------------------------------------------------------
# PDF text layer
# ---------------------------------------------------------------------------
#: Below this many characters per page, a PDF is a scan wearing a PDF wrapper.
#: A one-page GST invoice carries several hundred characters; the handful that a
#: scanned PDF yields comes from the producer's metadata, not the invoice.
MIN_CHARS_PER_PAGE: Final = 40

#: Pages read from one document. An invoice is one to three; a 400-page statement
#: uploaded by mistake should not be able to exhaust memory.
MAX_PDF_PAGES: Final = 10


class PdfTextLayerEngine:
    """Reads the embedded text layer of a digital PDF.

    Not OCR at all, which is exactly why it goes first: the characters are the ones
    the supplier's software wrote, so there is nothing to misrecognise.
    """

    name = "pdf-text-layer"

    def supports(self, fmt: DocumentFormat) -> bool:
        return fmt is DocumentFormat.PDF

    def is_available(self) -> bool:
        try:
            import pypdf  # noqa: F401
        except ImportError:
            return False
        return True

    def recognise(self, data: bytes, fmt: DocumentFormat) -> OcrResult:
        from pypdf import PdfReader
        from pypdf.errors import PdfReadError

        try:
            reader = PdfReader(io.BytesIO(data))
            # An empty user password is the common case for invoices that are merely
            # "protected" against editing rather than genuinely secret.
            if reader.is_encrypted and reader.decrypt("") == 0:
                raise ValidationError(
                    "That PDF is password-protected. Remove the password and upload it again.",
                    code="pdf_encrypted",
                )

            pages = reader.pages[:MAX_PDF_PAGES]
            texts = [page.extract_text() or "" for page in pages]
        except PdfReadError as exc:
            raise ValidationError(
                "That PDF could not be read - the file may be corrupt.",
                code="pdf_unreadable",
            ) from exc

        text = "\n".join(texts).strip()
        page_count = len(pages)

        if page_count and len(text) < MIN_CHARS_PER_PAGE * page_count:
            raise ScannedPdfError

        return OcrResult(
            text=text,
            engine=self.name,
            mean_confidence=Decimal("1.00"),
            page_count=page_count,
            is_exact=True,
        )


# ---------------------------------------------------------------------------
# Tesseract
# ---------------------------------------------------------------------------
#: Decompression-bomb ceiling. A4 at 600 dpi is ~35 MP, so 60 MP accepts any real
#: scan while refusing the 2 GB in-memory bitmap that a small crafted PNG can
#: decode to.
MAX_IMAGE_PIXELS: Final = 60_000_000

#: Tesseract needs glyphs roughly 20 px tall. Phone photos and email attachments
#: are routinely smaller, and upscaling before recognition measurably improves the
#: read - cheaper than asking the user to re-scan.
MIN_LONG_EDGE: Final = 1_200


class TesseractEngine:
    """Recognises text in an image using the Tesseract binary."""

    name = "tesseract"

    def supports(self, fmt: DocumentFormat) -> bool:
        return fmt.is_image

    def is_available(self) -> bool:
        """Probe the wrapper *and* the binary it shells out to.

        The wrapper importing proves nothing - it is the binary that does the work,
        and it is a separate system install that is frequently absent.
        """
        try:
            import pytesseract
            from PIL import Image  # noqa: F401
        except ImportError:
            return False

        self._configure(pytesseract)
        try:
            pytesseract.get_tesseract_version()
        except Exception:
            # Deliberately broad. This is a probe, and every way of failing to reach
            # the binary - not installed, wrong architecture, no execute permission,
            # a wrapper version raising something new - has the same answer: no.
            return False
        return True

    @staticmethod
    def _configure(pytesseract_module: object) -> None:
        """Point the wrapper at an explicitly configured binary, if there is one.

        Windows installers do not add Tesseract to ``PATH``, so ``which`` finds
        nothing on a machine where it is plainly installed. The setting exists for
        that case; when it is blank, ``PATH`` lookup is left alone.
        """
        configured = settings.tesseract_cmd.strip()
        if configured:
            pytesseract_module.pytesseract.tesseract_cmd = configured  # type: ignore[attr-defined]

    def recognise(self, data: bytes, fmt: DocumentFormat) -> OcrResult:
        import pytesseract
        from PIL import Image, UnidentifiedImageError

        self._configure(pytesseract)
        Image.MAX_IMAGE_PIXELS = MAX_IMAGE_PIXELS

        try:
            image = Image.open(io.BytesIO(data))
            # `open` only parses the header; `load` decodes the pixels. Both have to
            # be inside the guard, because a file with a valid magic number and a
            # damaged body - a browser upload cut short by a dropped connection - gets
            # past `open` and fails here.
            image.load()
        except Image.DecompressionBombError as exc:
            raise DocumentTooLargeError(
                "That image is too large to process safely.",
                code="image_too_many_pixels",
            ) from exc
        except (UnidentifiedImageError, OSError, ValueError, SyntaxError) as exc:
            # Pillow signals a damaged file with plain `OSError` ("Truncated File
            # Read"), and individual decoders raise `SyntaxError` or `ValueError`.
            # Letting any of them escape turns a bad upload into a 500.
            raise UnsupportedDocumentError(
                "That image could not be read - the file may be incomplete or corrupt.",
                code="image_unreadable",
            ) from exc

        prepared = self._prepare(image)

        try:
            # One pass, not two. `image_to_string` and `image_to_data` each run the
            # engine, so calling both would double the cost of the slowest step in
            # the pipeline; the text is reassembled from the word boxes instead.
            words = pytesseract.image_to_data(
                prepared,
                lang=settings.ocr_languages,
                output_type=pytesseract.Output.DICT,
                timeout=settings.ocr_timeout_seconds,
            )
        except RuntimeError as exc:
            # pytesseract raises RuntimeError on its own timeout.
            raise BusinessRuleError(
                "Reading that document took too long. Try a smaller or clearer image.",
                code="ocr_timeout",
            ) from exc
        except pytesseract.TesseractError as exc:
            log.warning("tesseract failed", extra={"error": str(exc)})
            raise NoTextRecognisedError from exc

        text = _reassemble_lines(words)
        confidence = _mean_confidence(words)

        return OcrResult(
            text=text,
            engine=self.name,
            mean_confidence=confidence,
            page_count=1,
        )

    @staticmethod
    def _prepare(image: object) -> object:
        """Grayscale, and upscale if the text is likely too small to read.

        Modest on purpose. Aggressive binarisation and deskewing help some scans and
        destroy others, and without OpenCV there is no way to choose per image - so
        this does only the two transforms that are safe across the board.
        """
        from PIL import Image

        assert isinstance(image, Image.Image)  # noqa: S101 - narrowing for mypy

        # Flatten transparency onto white: an alpha channel becomes black in
        # grayscale, which turns white text-on-transparent into black-on-black.
        if image.mode in ("RGBA", "LA", "P"):
            rgb = Image.new("RGB", image.size, (255, 255, 255))
            converted = image.convert("RGBA")
            rgb.paste(converted, mask=converted.split()[-1])
            image = rgb

        image = image.convert("L")

        long_edge = max(image.size)
        if 0 < long_edge < MIN_LONG_EDGE:
            scale = MIN_LONG_EDGE / long_edge
            image = image.resize(
                (round(image.width * scale), round(image.height * scale)),
                Image.Resampling.LANCZOS,
            )

        return image


#: Tesseract's ``image_to_data`` dict: parallel lists keyed by column name. Typed
#: loosely because the wrapper ships no stubs, and the values are a mix of ``str``
#: and ``int`` depending on the column.
type WordBoxes = dict[str, list[Any]]


def _reassemble_lines(words: WordBoxes) -> str:
    """Rebuild line-structured text from Tesseract's word boxes.

    Line structure is load-bearing downstream: the supplier's name is found by
    looking at the top few *lines*, and every label-to-value match ("Total:" then
    the figure) depends on the two staying on one line. A flat bag of words would
    lose both.
    """
    grouped: dict[tuple[int, int, int, int], list[str]] = {}
    order: list[tuple[int, int, int, int]] = []

    texts = words.get("text", [])
    for index, raw in enumerate(texts):
        token = str(raw).strip()
        if not token:
            continue
        key = (
            int(words["page_num"][index]),
            int(words["block_num"][index]),
            int(words["par_num"][index]),
            int(words["line_num"][index]),
        )
        if key not in grouped:
            grouped[key] = []
            order.append(key)
        grouped[key].append(token)

    return "\n".join(" ".join(grouped[key]) for key in order)


def _mean_confidence(words: WordBoxes) -> Decimal | None:
    """Mean confidence over recognised words, as a 0-1 fraction.

    Only words with actual text count. Tesseract emits ``-1`` for layout regions
    that contain no word, and averaging those in drags every score toward zero,
    making a clean scan look unreadable.
    """
    scores: list[Decimal] = []
    texts = words.get("text", [])
    confidences = words.get("conf", [])

    for index, raw in enumerate(texts):
        if not str(raw).strip():
            continue
        try:
            value = Decimal(str(confidences[index]))
        except (IndexError, ArithmeticError, ValueError):
            continue
        if value >= 0:
            scores.append(value)

    if not scores:
        return None
    return (sum(scores, Decimal("0")) / Decimal(len(scores)) / Decimal("100")).quantize(
        Decimal("0.0001")
    )


# ---------------------------------------------------------------------------
# Dispatch
# ---------------------------------------------------------------------------
#: Ordered by preference: exact text before recognised pixels.
ENGINES: Final[tuple[OcrEngine, ...]] = (PdfTextLayerEngine(), TesseractEngine())


def available_engines() -> list[str]:
    """Names of the engines this deployment can actually use.

    Surfaced through the API so an operator can tell "OCR is broken" from
    "Tesseract was never installed" without reading server logs.
    """
    return [engine.name for engine in ENGINES if engine.is_available()]


def supported_formats() -> list[DocumentFormat]:
    """Formats at least one available engine can read."""
    return [
        fmt
        for fmt in DocumentFormat
        if any(engine.supports(fmt) and engine.is_available() for engine in ENGINES)
    ]


def recognise_sync(data: bytes, fmt: DocumentFormat) -> OcrResult:
    """Recognise text using the first available engine for the format.

    Synchronous entry point, kept public so tests and any future CLI can call it
    without an event loop.
    """
    if not settings.ocr_enabled:
        raise EngineUnavailableError("Document scanning is disabled on this server.")

    candidates = [engine for engine in ENGINES if engine.supports(fmt)]
    if not candidates:
        raise UnsupportedDocumentError

    usable = [engine for engine in candidates if engine.is_available()]
    if not usable:
        raise EngineUnavailableError(
            f"No engine on this server can read {fmt.extension.upper()} files. "
            "Install Tesseract, or the `ocr` extra, to enable it."
        )

    result = usable[0].recognise(data, fmt)
    if result.is_empty:
        raise NoTextRecognisedError

    log.info(
        "document recognised",
        extra={
            "engine": result.engine,
            "pages": result.page_count,
            "characters": len(result.text),
            "mean_confidence": str(result.mean_confidence),
        },
    )
    return result


async def recognise(data: bytes, fmt: DocumentFormat) -> OcrResult:
    """Recognise text off the event loop.

    Tesseract is a blocking subprocess that takes seconds per page. Awaiting it in
    a thread is what keeps the rest of the application responsive while a document
    is being read - on the single-worker deployment this product targets, doing it
    inline would freeze every other request.
    """
    return await anyio.to_thread.run_sync(recognise_sync, data, fmt)
