"""sales customers leads quotations orders invoices payments

Revision ID: 9b90a7cc08bf
Revises: a1f2e3d4c5b6
Created: 2026-07-29 09:17:51.302402+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "9b90a7cc08bf"
down_revision: str | None = "a1f2e3d4c5b6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customer",
        sa.Column("code", sa.String(length=30), nullable=False),
        sa.Column("name", sa.String(length=250), nullable=False),
        sa.Column("legal_name", sa.String(length=250), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("website", sa.String(length=255), nullable=True),
        sa.Column("contact_person", sa.String(length=200), nullable=True),
        sa.Column("gstin", sa.String(length=15), nullable=True),
        sa.Column("pan", sa.String(length=10), nullable=True),
        sa.Column("state_code", sa.String(length=2), nullable=True),
        sa.Column("is_tax_exempt", sa.Boolean(), nullable=False),
        sa.Column("billing_address_line1", sa.String(length=255), nullable=True),
        sa.Column("billing_address_line2", sa.String(length=255), nullable=True),
        sa.Column("billing_city", sa.String(length=100), nullable=True),
        sa.Column("billing_state", sa.String(length=100), nullable=True),
        sa.Column("billing_postal_code", sa.String(length=20), nullable=True),
        sa.Column("billing_country", sa.String(length=2), nullable=False),
        sa.Column("shipping_address_line1", sa.String(length=255), nullable=True),
        sa.Column("shipping_address_line2", sa.String(length=255), nullable=True),
        sa.Column("shipping_city", sa.String(length=100), nullable=True),
        sa.Column("shipping_state", sa.String(length=100), nullable=True),
        sa.Column("shipping_postal_code", sa.String(length=20), nullable=True),
        sa.Column("shipping_country", sa.String(length=2), nullable=True),
        sa.Column("payment_terms_days", sa.Integer(), nullable=False),
        sa.Column("credit_limit", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("default_discount_percent", sa.Numeric(precision=9, scale=4), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("credit_limit >= 0", name=op.f("ck_customer_credit_limit_non_negative")),
        sa.CheckConstraint("payment_terms_days >= 0", name=op.f("ck_customer_terms_non_negative")),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_customer_organization_id_organization"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customer")),
        sa.UniqueConstraint("organization_id", "code", name="uq_customer_org_code"),
    )
    op.create_index(op.f("ix_customer_created_at"), "customer", ["created_at"], unique=False)
    op.create_index(op.f("ix_customer_deleted_at"), "customer", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_customer_email"), "customer", ["email"], unique=False)
    op.create_index(op.f("ix_customer_gstin"), "customer", ["gstin"], unique=False)
    op.create_index(op.f("ix_customer_name"), "customer", ["name"], unique=False)
    op.create_index("ix_customer_org_name", "customer", ["organization_id", "name"], unique=False)
    op.create_index(
        op.f("ix_customer_organization_id"), "customer", ["organization_id"], unique=False
    )
    op.create_table(
        "lead",
        sa.Column("name", sa.String(length=250), nullable=False),
        sa.Column("company", sa.String(length=250), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "new",
                "contacted",
                "qualified",
                "proposal_sent",
                "won",
                "lost",
                name="leadstatus",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("source", sa.String(length=100), nullable=True),
        sa.Column("estimated_value", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("expected_close_date", sa.Date(), nullable=True),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("last_contacted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("converted_customer_id", sa.UUID(), nullable=True),
        sa.Column("converted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lost_reason", sa.String(length=500), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("estimated_value >= 0", name=op.f("ck_lead_value_non_negative")),
        sa.ForeignKeyConstraint(
            ["converted_customer_id"],
            ["customer.id"],
            name=op.f("fk_lead_converted_customer_id_customer"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_lead_organization_id_organization"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["app_user.id"],
            name=op.f("fk_lead_owner_id_app_user"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lead")),
    )
    op.create_index(op.f("ix_lead_created_at"), "lead", ["created_at"], unique=False)
    op.create_index(op.f("ix_lead_deleted_at"), "lead", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_lead_email"), "lead", ["email"], unique=False)
    op.create_index(op.f("ix_lead_name"), "lead", ["name"], unique=False)
    op.create_index("ix_lead_org_status", "lead", ["organization_id", "status"], unique=False)
    op.create_index(op.f("ix_lead_organization_id"), "lead", ["organization_id"], unique=False)
    op.create_index(op.f("ix_lead_owner_id"), "lead", ["owner_id"], unique=False)
    op.create_index(op.f("ix_lead_status"), "lead", ["status"], unique=False)
    op.create_table(
        "quotation",
        sa.Column("quotation_number", sa.String(length=50), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column("lead_id", sa.UUID(), nullable=True),
        sa.Column("quotation_date", sa.Date(), nullable=False),
        sa.Column("valid_until", sa.Date(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "sent",
                "accepted",
                "rejected",
                "expired",
                "converted",
                name="quotationstatus",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("subtotal", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("discount_total", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("taxable_total", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("cgst_total", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("sgst_total", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("igst_total", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("tax_total", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("round_off", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("grand_total", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "tax_treatment",
            sa.Enum(
                "intra_state",
                "inter_state",
                "export",
                "exempt",
                name="taxtreatment",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("terms", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "cgst_total + sgst_total + igst_total = tax_total",
            name=op.f("ck_quotation_quotation_tax_split_reconciles"),
        ),
        sa.CheckConstraint(
            "grand_total >= 0", name=op.f("ck_quotation_quotation_total_non_negative")
        ),
        sa.CheckConstraint(
            "taxable_total + tax_total + round_off = grand_total",
            name=op.f("ck_quotation_quotation_total_reconciles"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["app_user.id"],
            name=op.f("fk_quotation_created_by_id_app_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customer.id"],
            name=op.f("fk_quotation_customer_id_customer"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"], ["lead.id"], name=op.f("fk_quotation_lead_id_lead"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_quotation_organization_id_organization"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quotation")),
        sa.UniqueConstraint("organization_id", "quotation_number", name="uq_quotation_org_number"),
    )
    op.create_index(op.f("ix_quotation_created_at"), "quotation", ["created_at"], unique=False)
    op.create_index(op.f("ix_quotation_customer_id"), "quotation", ["customer_id"], unique=False)
    op.create_index(op.f("ix_quotation_deleted_at"), "quotation", ["deleted_at"], unique=False)
    op.create_index(
        op.f("ix_quotation_organization_id"), "quotation", ["organization_id"], unique=False
    )
    op.create_index(
        op.f("ix_quotation_quotation_date"), "quotation", ["quotation_date"], unique=False
    )
    op.create_index(
        op.f("ix_quotation_quotation_number"), "quotation", ["quotation_number"], unique=False
    )
    op.create_index(op.f("ix_quotation_status"), "quotation", ["status"], unique=False)
    op.create_table(
        "payment",
        sa.Column("payment_number", sa.String(length=50), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column("payment_date", sa.Date(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("unallocated_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column(
            "method",
            sa.Enum(
                "cash",
                "bank_transfer",
                "cheque",
                "upi",
                "card",
                "other",
                name="paymentmethod",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("reference", sa.String(length=100), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("deposit_account_id", sa.UUID(), nullable=True),
        sa.Column("journal_entry_id", sa.UUID(), nullable=True),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("amount > 0", name=op.f("ck_payment_amount_positive")),
        sa.CheckConstraint(
            "unallocated_amount >= 0 AND unallocated_amount <= amount",
            name=op.f("ck_payment_unallocated_within_amount"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["app_user.id"],
            name=op.f("fk_payment_created_by_id_app_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customer.id"],
            name=op.f("fk_payment_customer_id_customer"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["deposit_account_id"],
            ["account.id"],
            name=op.f("fk_payment_deposit_account_id_account"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["journal_entry_id"],
            ["journal_entry.id"],
            name=op.f("fk_payment_journal_entry_id_journal_entry"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_payment_organization_id_organization"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment")),
        sa.UniqueConstraint("organization_id", "payment_number", name="uq_payment_org_number"),
    )
    op.create_index(op.f("ix_payment_created_at"), "payment", ["created_at"], unique=False)
    op.create_index(op.f("ix_payment_customer_id"), "payment", ["customer_id"], unique=False)
    op.create_index(op.f("ix_payment_deleted_at"), "payment", ["deleted_at"], unique=False)
    op.create_index(
        op.f("ix_payment_organization_id"), "payment", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_payment_payment_date"), "payment", ["payment_date"], unique=False)
    op.create_index(op.f("ix_payment_payment_number"), "payment", ["payment_number"], unique=False)
    op.create_table(
        "quotation_line",
        sa.Column("quotation_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("line_number", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("hsn_code", sa.String(length=10), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("unit", sa.String(length=20), nullable=True),
        sa.Column("unit_price", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("discount_percent", sa.Numeric(precision=9, scale=4), nullable=False),
        sa.Column("discount_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("tax_rate", sa.Numeric(precision=9, scale=4), nullable=False),
        sa.Column("cgst_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("sgst_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("igst_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("gross_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("taxable_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("tax_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("line_total", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "cgst_amount + sgst_amount + igst_amount = tax_amount",
            name=op.f("ck_quotation_line_quotation_line_tax_split_reconciles"),
        ),
        sa.CheckConstraint(
            "discount_amount >= 0",
            name=op.f("ck_quotation_line_quotation_line_discount_non_negative"),
        ),
        sa.CheckConstraint(
            "quantity > 0", name=op.f("ck_quotation_line_quotation_line_quantity_positive")
        ),
        sa.CheckConstraint(
            "tax_rate >= 0 AND tax_rate <= 100",
            name=op.f("ck_quotation_line_quotation_line_tax_rate_range"),
        ),
        sa.CheckConstraint(
            "taxable_amount + tax_amount = line_total",
            name=op.f("ck_quotation_line_quotation_line_total_reconciles"),
        ),
        sa.CheckConstraint(
            "unit_price >= 0", name=op.f("ck_quotation_line_quotation_line_price_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["quotation_id"],
            ["quotation.id"],
            name=op.f("fk_quotation_line_quotation_id_quotation"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quotation_line")),
    )
    op.create_index(
        op.f("ix_quotation_line_created_at"), "quotation_line", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_quotation_line_quotation_id"), "quotation_line", ["quotation_id"], unique=False
    )
    op.create_table(
        "sales_order",
        sa.Column("order_number", sa.String(length=50), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column("quotation_id", sa.UUID(), nullable=True),
        sa.Column("order_date", sa.Date(), nullable=False),
        sa.Column("expected_delivery_date", sa.Date(), nullable=True),
        sa.Column("customer_reference", sa.String(length=100), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "confirmed",
                "partially_invoiced",
                "invoiced",
                "cancelled",
                name="salesorderstatus",
                native_enum=False,
                create_constraint=True,
                length=25,
            ),
            nullable=False,
        ),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("invoiced_total", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("subtotal", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("discount_total", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("taxable_total", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("cgst_total", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("sgst_total", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("igst_total", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("tax_total", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("round_off", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("grand_total", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "tax_treatment",
            sa.Enum(
                "intra_state",
                "inter_state",
                "export",
                "exempt",
                name="taxtreatment",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("terms", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "cgst_total + sgst_total + igst_total = tax_total",
            name=op.f("ck_sales_order_sales_order_tax_split_reconciles"),
        ),
        sa.CheckConstraint(
            "grand_total >= 0", name=op.f("ck_sales_order_sales_order_total_non_negative")
        ),
        sa.CheckConstraint(
            "invoiced_total >= 0", name=op.f("ck_sales_order_invoiced_non_negative")
        ),
        sa.CheckConstraint(
            "taxable_total + tax_total + round_off = grand_total",
            name=op.f("ck_sales_order_sales_order_total_reconciles"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["app_user.id"],
            name=op.f("fk_sales_order_created_by_id_app_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customer.id"],
            name=op.f("fk_sales_order_customer_id_customer"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_sales_order_organization_id_organization"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["quotation_id"],
            ["quotation.id"],
            name=op.f("fk_sales_order_quotation_id_quotation"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sales_order")),
        sa.UniqueConstraint("organization_id", "order_number", name="uq_sales_order_org_number"),
    )
    op.create_index(op.f("ix_sales_order_created_at"), "sales_order", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_sales_order_customer_id"), "sales_order", ["customer_id"], unique=False
    )
    op.create_index(op.f("ix_sales_order_deleted_at"), "sales_order", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_sales_order_order_date"), "sales_order", ["order_date"], unique=False)
    op.create_index(
        op.f("ix_sales_order_order_number"), "sales_order", ["order_number"], unique=False
    )
    op.create_index(
        op.f("ix_sales_order_organization_id"), "sales_order", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_sales_order_status"), "sales_order", ["status"], unique=False)
    op.create_table(
        "invoice",
        sa.Column("invoice_number", sa.String(length=50), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column("sales_order_id", sa.UUID(), nullable=True),
        sa.Column("invoice_date", sa.Date(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "posted",
                "partially_paid",
                "paid",
                "cancelled",
                name="invoicestatus",
                native_enum=False,
                create_constraint=True,
                length=25,
            ),
            nullable=False,
        ),
        sa.Column("paid_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("journal_entry_id", sa.UUID(), nullable=True),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reversal_entry_id", sa.UUID(), nullable=True),
        sa.Column("customer_gstin", sa.String(length=15), nullable=True),
        sa.Column("place_of_supply", sa.String(length=2), nullable=True),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("subtotal", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("discount_total", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("taxable_total", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("cgst_total", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("sgst_total", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("igst_total", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("tax_total", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("round_off", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("grand_total", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "tax_treatment",
            sa.Enum(
                "intra_state",
                "inter_state",
                "export",
                "exempt",
                name="taxtreatment",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("terms", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(status = 'draft' AND journal_entry_id IS NULL) OR (status <> 'draft' AND journal_entry_id IS NOT NULL)",
            name=op.f("ck_invoice_posted_has_journal_entry"),
        ),
        sa.CheckConstraint(
            "cgst_total + sgst_total + igst_total = tax_total",
            name=op.f("ck_invoice_invoice_tax_split_reconciles"),
        ),
        sa.CheckConstraint("due_date >= invoice_date", name=op.f("ck_invoice_due_after_issue")),
        sa.CheckConstraint("grand_total >= 0", name=op.f("ck_invoice_invoice_total_non_negative")),
        sa.CheckConstraint("paid_amount <= grand_total", name=op.f("ck_invoice_paid_within_total")),
        sa.CheckConstraint("paid_amount >= 0", name=op.f("ck_invoice_paid_non_negative")),
        sa.CheckConstraint(
            "taxable_total + tax_total + round_off = grand_total",
            name=op.f("ck_invoice_invoice_total_reconciles"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["app_user.id"],
            name=op.f("fk_invoice_created_by_id_app_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customer.id"],
            name=op.f("fk_invoice_customer_id_customer"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["journal_entry_id"],
            ["journal_entry.id"],
            name=op.f("fk_invoice_journal_entry_id_journal_entry"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_invoice_organization_id_organization"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reversal_entry_id"],
            ["journal_entry.id"],
            name=op.f("fk_invoice_reversal_entry_id_journal_entry"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sales_order_id"],
            ["sales_order.id"],
            name=op.f("fk_invoice_sales_order_id_sales_order"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invoice")),
        sa.UniqueConstraint("organization_id", "invoice_number", name="uq_invoice_org_number"),
    )
    op.create_index(op.f("ix_invoice_created_at"), "invoice", ["created_at"], unique=False)
    op.create_index(op.f("ix_invoice_customer_id"), "invoice", ["customer_id"], unique=False)
    op.create_index(op.f("ix_invoice_deleted_at"), "invoice", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_invoice_due_date"), "invoice", ["due_date"], unique=False)
    op.create_index(op.f("ix_invoice_invoice_date"), "invoice", ["invoice_date"], unique=False)
    op.create_index(op.f("ix_invoice_invoice_number"), "invoice", ["invoice_number"], unique=False)
    op.create_index(
        "ix_invoice_org_status_due",
        "invoice",
        ["organization_id", "status", "due_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_invoice_organization_id"), "invoice", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_invoice_status"), "invoice", ["status"], unique=False)
    op.create_table(
        "sales_order_line",
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("line_number", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("hsn_code", sa.String(length=10), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("unit", sa.String(length=20), nullable=True),
        sa.Column("unit_price", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("discount_percent", sa.Numeric(precision=9, scale=4), nullable=False),
        sa.Column("discount_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("tax_rate", sa.Numeric(precision=9, scale=4), nullable=False),
        sa.Column("cgst_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("sgst_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("igst_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("gross_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("taxable_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("tax_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("line_total", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "cgst_amount + sgst_amount + igst_amount = tax_amount",
            name=op.f("ck_sales_order_line_sales_order_line_tax_split_reconciles"),
        ),
        sa.CheckConstraint(
            "discount_amount >= 0",
            name=op.f("ck_sales_order_line_sales_order_line_discount_non_negative"),
        ),
        sa.CheckConstraint(
            "quantity > 0", name=op.f("ck_sales_order_line_sales_order_line_quantity_positive")
        ),
        sa.CheckConstraint(
            "tax_rate >= 0 AND tax_rate <= 100",
            name=op.f("ck_sales_order_line_sales_order_line_tax_rate_range"),
        ),
        sa.CheckConstraint(
            "taxable_amount + tax_amount = line_total",
            name=op.f("ck_sales_order_line_sales_order_line_total_reconciles"),
        ),
        sa.CheckConstraint(
            "unit_price >= 0", name=op.f("ck_sales_order_line_sales_order_line_price_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["sales_order.id"],
            name=op.f("fk_sales_order_line_order_id_sales_order"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sales_order_line")),
    )
    op.create_index(
        op.f("ix_sales_order_line_created_at"), "sales_order_line", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_sales_order_line_order_id"), "sales_order_line", ["order_id"], unique=False
    )
    op.create_table(
        "invoice_line",
        sa.Column("invoice_id", sa.UUID(), nullable=False),
        sa.Column("revenue_account_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("line_number", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("hsn_code", sa.String(length=10), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("unit", sa.String(length=20), nullable=True),
        sa.Column("unit_price", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("discount_percent", sa.Numeric(precision=9, scale=4), nullable=False),
        sa.Column("discount_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("tax_rate", sa.Numeric(precision=9, scale=4), nullable=False),
        sa.Column("cgst_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("sgst_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("igst_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("gross_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("taxable_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("tax_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("line_total", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "cgst_amount + sgst_amount + igst_amount = tax_amount",
            name=op.f("ck_invoice_line_invoice_line_tax_split_reconciles"),
        ),
        sa.CheckConstraint(
            "discount_amount >= 0", name=op.f("ck_invoice_line_invoice_line_discount_non_negative")
        ),
        sa.CheckConstraint(
            "quantity > 0", name=op.f("ck_invoice_line_invoice_line_quantity_positive")
        ),
        sa.CheckConstraint(
            "tax_rate >= 0 AND tax_rate <= 100",
            name=op.f("ck_invoice_line_invoice_line_tax_rate_range"),
        ),
        sa.CheckConstraint(
            "taxable_amount + tax_amount = line_total",
            name=op.f("ck_invoice_line_invoice_line_total_reconciles"),
        ),
        sa.CheckConstraint(
            "unit_price >= 0", name=op.f("ck_invoice_line_invoice_line_price_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoice.id"],
            name=op.f("fk_invoice_line_invoice_id_invoice"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["revenue_account_id"],
            ["account.id"],
            name=op.f("fk_invoice_line_revenue_account_id_account"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invoice_line")),
    )
    op.create_index(
        op.f("ix_invoice_line_created_at"), "invoice_line", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_invoice_line_invoice_id"), "invoice_line", ["invoice_id"], unique=False
    )
    op.create_table(
        "payment_allocation",
        sa.Column("payment_id", sa.UUID(), nullable=False),
        sa.Column("invoice_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "amount > 0", name=op.f("ck_payment_allocation_allocation_amount_positive")
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoice.id"],
            name=op.f("fk_payment_allocation_invoice_id_invoice"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["payment_id"],
            ["payment.id"],
            name=op.f("fk_payment_allocation_payment_id_payment"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment_allocation")),
        sa.UniqueConstraint("payment_id", "invoice_id", name="uq_allocation_payment_invoice"),
    )
    op.create_index(
        op.f("ix_payment_allocation_created_at"), "payment_allocation", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_payment_allocation_invoice_id"), "payment_allocation", ["invoice_id"], unique=False
    )
    op.create_index(
        op.f("ix_payment_allocation_payment_id"), "payment_allocation", ["payment_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_payment_allocation_payment_id"), table_name="payment_allocation")
    op.drop_index(op.f("ix_payment_allocation_invoice_id"), table_name="payment_allocation")
    op.drop_index(op.f("ix_payment_allocation_created_at"), table_name="payment_allocation")
    op.drop_table("payment_allocation")
    op.drop_index(op.f("ix_invoice_line_invoice_id"), table_name="invoice_line")
    op.drop_index(op.f("ix_invoice_line_created_at"), table_name="invoice_line")
    op.drop_table("invoice_line")
    op.drop_index(op.f("ix_sales_order_line_order_id"), table_name="sales_order_line")
    op.drop_index(op.f("ix_sales_order_line_created_at"), table_name="sales_order_line")
    op.drop_table("sales_order_line")
    op.drop_index(op.f("ix_invoice_status"), table_name="invoice")
    op.drop_index(op.f("ix_invoice_organization_id"), table_name="invoice")
    op.drop_index("ix_invoice_org_status_due", table_name="invoice")
    op.drop_index(op.f("ix_invoice_invoice_number"), table_name="invoice")
    op.drop_index(op.f("ix_invoice_invoice_date"), table_name="invoice")
    op.drop_index(op.f("ix_invoice_due_date"), table_name="invoice")
    op.drop_index(op.f("ix_invoice_deleted_at"), table_name="invoice")
    op.drop_index(op.f("ix_invoice_customer_id"), table_name="invoice")
    op.drop_index(op.f("ix_invoice_created_at"), table_name="invoice")
    op.drop_table("invoice")
    op.drop_index(op.f("ix_sales_order_status"), table_name="sales_order")
    op.drop_index(op.f("ix_sales_order_organization_id"), table_name="sales_order")
    op.drop_index(op.f("ix_sales_order_order_number"), table_name="sales_order")
    op.drop_index(op.f("ix_sales_order_order_date"), table_name="sales_order")
    op.drop_index(op.f("ix_sales_order_deleted_at"), table_name="sales_order")
    op.drop_index(op.f("ix_sales_order_customer_id"), table_name="sales_order")
    op.drop_index(op.f("ix_sales_order_created_at"), table_name="sales_order")
    op.drop_table("sales_order")
    op.drop_index(op.f("ix_quotation_line_quotation_id"), table_name="quotation_line")
    op.drop_index(op.f("ix_quotation_line_created_at"), table_name="quotation_line")
    op.drop_table("quotation_line")
    op.drop_index(op.f("ix_payment_payment_number"), table_name="payment")
    op.drop_index(op.f("ix_payment_payment_date"), table_name="payment")
    op.drop_index(op.f("ix_payment_organization_id"), table_name="payment")
    op.drop_index(op.f("ix_payment_deleted_at"), table_name="payment")
    op.drop_index(op.f("ix_payment_customer_id"), table_name="payment")
    op.drop_index(op.f("ix_payment_created_at"), table_name="payment")
    op.drop_table("payment")
    op.drop_index(op.f("ix_quotation_status"), table_name="quotation")
    op.drop_index(op.f("ix_quotation_quotation_number"), table_name="quotation")
    op.drop_index(op.f("ix_quotation_quotation_date"), table_name="quotation")
    op.drop_index(op.f("ix_quotation_organization_id"), table_name="quotation")
    op.drop_index(op.f("ix_quotation_deleted_at"), table_name="quotation")
    op.drop_index(op.f("ix_quotation_customer_id"), table_name="quotation")
    op.drop_index(op.f("ix_quotation_created_at"), table_name="quotation")
    op.drop_table("quotation")
    op.drop_index(op.f("ix_lead_status"), table_name="lead")
    op.drop_index(op.f("ix_lead_owner_id"), table_name="lead")
    op.drop_index(op.f("ix_lead_organization_id"), table_name="lead")
    op.drop_index("ix_lead_org_status", table_name="lead")
    op.drop_index(op.f("ix_lead_name"), table_name="lead")
    op.drop_index(op.f("ix_lead_email"), table_name="lead")
    op.drop_index(op.f("ix_lead_deleted_at"), table_name="lead")
    op.drop_index(op.f("ix_lead_created_at"), table_name="lead")
    op.drop_table("lead")
    op.drop_index(op.f("ix_customer_organization_id"), table_name="customer")
    op.drop_index("ix_customer_org_name", table_name="customer")
    op.drop_index(op.f("ix_customer_name"), table_name="customer")
    op.drop_index(op.f("ix_customer_gstin"), table_name="customer")
    op.drop_index(op.f("ix_customer_email"), table_name="customer")
    op.drop_index(op.f("ix_customer_deleted_at"), table_name="customer")
    op.drop_index(op.f("ix_customer_created_at"), table_name="customer")
    op.drop_table("customer")
    # ### end Alembic commands ###
