"""journal entry counterparty

Adds the "particulars" column of a traditional day book: who the money came from, or
went to. Free text and nullable, deliberately not a foreign key to a customer or
supplier - most parties in a small business are the auto driver or the electricity
board, and requiring a master record before you can write down who paid you is the
friction the billing screen exists to remove.

Indexed because "everything I paid Airtel" is a question people ask. Additive and
nullable, so it is safe on a live table and fully reversible.


Revision ID: 1acf72193910
Revises: 9510b823b060
Created: 2026-07-29 13:57:19.341070+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "1acf72193910"
down_revision: str | None = "9510b823b060"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("journal_entry", sa.Column("counterparty", sa.String(length=200), nullable=True))
    op.create_index(
        op.f("ix_journal_entry_counterparty"), "journal_entry", ["counterparty"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_journal_entry_counterparty"), table_name="journal_entry")
    op.drop_column("journal_entry", "counterparty")
    # ### end Alembic commands ###
