"""document blobs in postgres

Document bytes move into the database. `document_blob` holds one compressed blob per
uploaded file, as `BYTEA`, replacing the local-filesystem backend entirely and demoting
S3-compatible object storage to an option nobody has to configure.

**Additive, and safe to apply before deploying the code.** Nothing on `document` changes -
`storage_path` already means "the key, whatever the backend" and keeps meaning exactly that.
So this migration cannot break a running instance: the old code does not know the table
exists, and the new code finds it empty and waits for uploads.

**It does not move existing bytes, and it must not.** A data migration here would have to
open a filesystem path or an S3 connection from inside a DDL transaction, where a network
timeout leaves the schema half-applied and an operator with no obvious way forward. Moving
blobs is a separate, resumable, verify-before-delete step:

    uv run python scripts/migrate_document_blobs.py --to database
    uv run python scripts/migrate_document_blobs.py --to database --purge

Until it runs, documents uploaded under the old backend read as "the stored file is missing"
while their rows, extracted fields and links to posted bills stay intact. That is the right
failure: recoverable by running the script, and it never silently returns the wrong bytes.

`compression` is a per-row CHECK-constrained string rather than a global setting, so changing
the default codec later cannot invalidate a byte already stored. Downgrading drops the table
and therefore the blobs, which is why the script above copies rather than moves by default.

Revision ID: 83f89950b919
Revises: 2dde7dff2c8d
Created: 2026-08-05 15:36:18.855571+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "83f89950b919"
down_revision: str | None = "2dde7dff2c8d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_blob",
        sa.Column("storage_key", sa.String(length=255), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("original_size", sa.Integer(), nullable=False),
        sa.Column("compressed_size", sa.Integer(), nullable=False),
        sa.Column(
            "compression",
            sa.Enum(
                "none", "zlib", name="codec", native_enum=False, create_constraint=True, length=20
            ),
            server_default=sa.text("'zlib'"),
            nullable=False,
        ),
        sa.Column("data", sa.LargeBinary(), nullable=False),
        sa.Column(
            "uploaded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("uploaded_by_user_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_document_blob_organization_id_organization"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_user_id"],
            ["app_user.id"],
            name=op.f("fk_document_blob_uploaded_by_user_id_app_user"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_blob")),
    )
    op.create_index(
        op.f("ix_document_blob_created_at"), "document_blob", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_document_blob_organization_id"), "document_blob", ["organization_id"], unique=False
    )
    op.create_index(
        "uq_document_blob_key", "document_blob", ["organization_id", "storage_key"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_document_blob_key", table_name="document_blob")
    op.drop_index(op.f("ix_document_blob_organization_id"), table_name="document_blob")
    op.drop_index(op.f("ix_document_blob_created_at"), table_name="document_blob")
    op.drop_table("document_blob")
    # ### end Alembic commands ###
