"""scanned documents

Revision ID: 9510b823b060
Revises: 7ef882650e50
Created: 2026-07-29 11:33:48.870363+00:00

The `document` table: an uploaded supplier invoice, what OCR read out of it, and
which bill it became.

Two indexes here are the feature, not tuning:

* ``uq_document_org_sha256`` - unique on ``(organization_id, sha256)`` where the row
  is live. The same bytes are the same document, so uploading a file twice returns
  the first one instead of creating a second. Partial on ``deleted_at`` so deleting a
  document does not permanently poison its own hash.
* ``ix_document_invoice_identity`` - ``(organization_id, supplier GSTIN, invoice
  number)``. Deliberately **not** unique: paying a supplier invoice twice is the most
  expensive clerical error in payables and must be surfaced, but the values indexed
  were read by an OCR engine, and refusing a genuine invoice because a digit was
  misread would make the feature worse than manual entry. It warns; it does not
  block.

``bill_id`` is ``ON DELETE RESTRICT`` rather than ``SET NULL``: a posted bill must
keep its source document reachable, and severing that link silently would leave an
entry in the books whose supporting evidence cannot be found.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "9510b823b060"
down_revision: str | None = "7ef882650e50"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document",
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column(
            "content_type",
            sa.Enum(
                "application/pdf",
                "image/png",
                "image/jpeg",
                "image/tiff",
                "image/webp",
                name="documentformat",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("storage_path", sa.String(length=255), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "purchase_invoice",
                "receipt",
                "quotation",
                "other",
                name="documentkind",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            server_default=sa.text("'purchase_invoice'"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "uploaded",
                "extracted",
                "confirmed",
                "rejected",
                "failed",
                name="documentstatus",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            server_default=sa.text("'uploaded'"),
            nullable=False,
        ),
        sa.Column("engine", sa.String(length=40), nullable=True),
        sa.Column("engine_confidence", sa.Numeric(precision=9, scale=4), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("recognised_text", sa.Text(), nullable=True),
        sa.Column("extracted_supplier_name", sa.String(length=250), nullable=True),
        sa.Column("extracted_supplier_gstin", sa.String(length=15), nullable=True),
        sa.Column("extracted_invoice_number", sa.String(length=50), nullable=True),
        sa.Column("extracted_invoice_date", sa.Date(), nullable=True),
        sa.Column("extracted_subtotal", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("extracted_tax_amount", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("extracted_total_amount", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column(
            "field_confidence",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("overall_confidence", sa.Numeric(precision=9, scale=4), nullable=True),
        sa.Column(
            "totals_reconcile", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("failure_code", sa.String(length=50), nullable=True),
        sa.Column("failure_message", sa.Text(), nullable=True),
        sa.Column("matched_supplier_id", sa.UUID(), nullable=True),
        sa.Column("bill_id", sa.UUID(), nullable=True),
        sa.Column("duplicate_of_id", sa.UUID(), nullable=True),
        sa.Column("uploaded_by_user_id", sa.UUID(), nullable=True),
        sa.Column("reviewed_by_user_id", sa.UUID(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["bill_id"], ["bill.id"], name=op.f("fk_document_bill_id_bill"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["duplicate_of_id"],
            ["document.id"],
            name=op.f("fk_document_duplicate_of_id_document"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["matched_supplier_id"],
            ["supplier.id"],
            name=op.f("fk_document_matched_supplier_id_supplier"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_document_organization_id_organization"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_user_id"],
            ["app_user.id"],
            name=op.f("fk_document_reviewed_by_user_id_app_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_user_id"],
            ["app_user.id"],
            name=op.f("fk_document_uploaded_by_user_id_app_user"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document")),
    )
    op.create_index(op.f("ix_document_bill_id"), "document", ["bill_id"], unique=False)
    op.create_index(op.f("ix_document_created_at"), "document", ["created_at"], unique=False)
    op.create_index(op.f("ix_document_deleted_at"), "document", ["deleted_at"], unique=False)
    op.create_index(
        "ix_document_invoice_identity",
        "document",
        ["organization_id", "extracted_supplier_gstin", "extracted_invoice_number"],
        unique=False,
        postgresql_where=sa.text("extracted_invoice_number IS NOT NULL"),
    )
    op.create_index(
        op.f("ix_document_matched_supplier_id"), "document", ["matched_supplier_id"], unique=False
    )
    op.create_index(
        op.f("ix_document_organization_id"), "document", ["organization_id"], unique=False
    )
    op.create_index(
        op.f("ix_document_overall_confidence"), "document", ["overall_confidence"], unique=False
    )
    op.create_index(
        "ix_document_review_queue",
        "document",
        ["organization_id", "status", "created_at"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(op.f("ix_document_sha256"), "document", ["sha256"], unique=False)
    op.create_index(op.f("ix_document_status"), "document", ["status"], unique=False)
    op.create_index(
        "uq_document_org_sha256",
        "document",
        ["organization_id", "sha256"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_document_org_sha256",
        table_name="document",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_document_status"), table_name="document")
    op.drop_index(op.f("ix_document_sha256"), table_name="document")
    op.drop_index(
        "ix_document_review_queue",
        table_name="document",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_document_overall_confidence"), table_name="document")
    op.drop_index(op.f("ix_document_organization_id"), table_name="document")
    op.drop_index(op.f("ix_document_matched_supplier_id"), table_name="document")
    op.drop_index(
        "ix_document_invoice_identity",
        table_name="document",
        postgresql_where=sa.text("extracted_invoice_number IS NOT NULL"),
    )
    op.drop_index(op.f("ix_document_deleted_at"), table_name="document")
    op.drop_index(op.f("ix_document_created_at"), table_name="document")
    op.drop_index(op.f("ix_document_bill_id"), table_name="document")
    op.drop_table("document")
    # ### end Alembic commands ###
