"""stock level carries authoritative total value

Revision ID: 7ef882650e50
Revises: 867711861952
Created: 2026-07-29 10:27:14.262738+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "7ef882650e50"
down_revision: str | None = "867711861952"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "stock_level", sa.Column("stock_value", sa.Numeric(precision=18, scale=4), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stock_level", "stock_value")
    # ### end Alembic commands ###
