"""accounting core

Revision ID: 7b9866d8ab7e
Revises: 90cd63df7440
Created: 2026-07-29 08:51:26.444301+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "7b9866d8ab7e"
down_revision: str | None = "90cd63df7440"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account",
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "account_type",
            sa.Enum(
                "ASSET",
                "LIABILITY",
                "EQUITY",
                "INCOME",
                "EXPENSE",
                name="accounttype",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "subtype",
            sa.Enum(
                "CASH",
                "BANK",
                "ACCOUNTS_RECEIVABLE",
                "INVENTORY",
                "OTHER_CURRENT_ASSET",
                "FIXED_ASSET",
                "ACCUMULATED_DEPRECIATION",
                "OTHER_ASSET",
                "ACCOUNTS_PAYABLE",
                "TAX_PAYABLE",
                "OTHER_CURRENT_LIABILITY",
                "LONG_TERM_LIABILITY",
                "CAPITAL",
                "DRAWINGS",
                "RETAINED_EARNINGS",
                "OPERATING_REVENUE",
                "OTHER_INCOME",
                "COST_OF_GOODS_SOLD",
                "OPERATING_EXPENSE",
                "PAYROLL_EXPENSE",
                "DEPRECIATION_EXPENSE",
                "TAX_EXPENSE",
                "OTHER_EXPENSE",
                name="accountsubtype",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("is_group", sa.Boolean(), nullable=False),
        sa.Column("depth", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column("system_key", sa.String(length=50), nullable=True),
        sa.Column("is_reconcilable", sa.Boolean(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_account_organization_id_organization"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["account.id"],
            name=op.f("fk_account_parent_id_account"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_account")),
        sa.UniqueConstraint("organization_id", "code", name="uq_account_org_code"),
    )
    op.create_index(op.f("ix_account_account_type"), "account", ["account_type"], unique=False)
    op.create_index(op.f("ix_account_created_at"), "account", ["created_at"], unique=False)
    op.create_index(op.f("ix_account_deleted_at"), "account", ["deleted_at"], unique=False)
    op.create_index(
        "ix_account_org_type", "account", ["organization_id", "account_type"], unique=False
    )
    op.create_index(
        op.f("ix_account_organization_id"), "account", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_account_parent_id"), "account", ["parent_id"], unique=False)
    op.create_index(
        "ix_account_postable",
        "account",
        ["organization_id"],
        unique=False,
        postgresql_where=sa.text("is_group IS FALSE AND is_active IS TRUE AND deleted_at IS NULL"),
    )
    op.create_index(
        "uq_account_org_system_key",
        "account",
        ["organization_id", "system_key"],
        unique=True,
        postgresql_where=sa.text("system_key IS NOT NULL"),
    )
    op.create_table(
        "fiscal_year",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("OPEN", "CLOSED", "LOCKED", name="periodstatus", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("end_date > start_date", name=op.f("ck_fiscal_year_dates_ordered")),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_fiscal_year_organization_id_organization"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fiscal_year")),
        sa.UniqueConstraint("organization_id", "name", name="uq_fiscal_year_org_name"),
    )
    op.create_index(op.f("ix_fiscal_year_created_at"), "fiscal_year", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_fiscal_year_organization_id"), "fiscal_year", ["organization_id"], unique=False
    )
    op.create_table(
        "number_sequence",
        sa.Column("scope", sa.String(length=120), nullable=False),
        sa.Column("prefix", sa.String(length=20), nullable=False),
        sa.Column("next_value", sa.Integer(), nullable=False),
        sa.Column("padding", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("next_value >= 1", name=op.f("ck_number_sequence_positive_next_value")),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_number_sequence_organization_id_organization"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_number_sequence")),
        sa.UniqueConstraint("organization_id", "scope", name="uq_number_sequence_org_scope"),
    )
    op.create_index(
        op.f("ix_number_sequence_created_at"), "number_sequence", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_number_sequence_organization_id"),
        "number_sequence",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "accounting_period",
        sa.Column("fiscal_year_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("OPEN", "CLOSED", "LOCKED", name="periodstatus", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_by_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "end_date >= start_date", name=op.f("ck_accounting_period_dates_ordered")
        ),
        sa.ForeignKeyConstraint(
            ["closed_by_id"],
            ["app_user.id"],
            name=op.f("fk_accounting_period_closed_by_id_app_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["fiscal_year_id"],
            ["fiscal_year.id"],
            name=op.f("fk_accounting_period_fiscal_year_id_fiscal_year"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_accounting_period_organization_id_organization"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_accounting_period")),
        sa.UniqueConstraint("fiscal_year_id", "name", name="uq_period_year_name"),
    )
    op.create_index(
        op.f("ix_accounting_period_created_at"), "accounting_period", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_accounting_period_end_date"), "accounting_period", ["end_date"], unique=False
    )
    op.create_index(
        op.f("ix_accounting_period_fiscal_year_id"),
        "accounting_period",
        ["fiscal_year_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_accounting_period_organization_id"),
        "accounting_period",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_period_org_range",
        "accounting_period",
        ["organization_id", "start_date", "end_date"],
        unique=False,
    )
    op.create_table(
        "journal",
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "journal_type",
            sa.Enum(
                "GENERAL",
                "SALES",
                "PURCHASE",
                "CASH",
                "BANK",
                "OPENING",
                name="journaltype",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("number_prefix", sa.String(length=10), nullable=False),
        sa.Column("default_account_id", sa.UUID(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["default_account_id"],
            ["account.id"],
            name=op.f("fk_journal_default_account_id_account"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_journal_organization_id_organization"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_journal")),
        sa.UniqueConstraint("organization_id", "code", name="uq_journal_org_code"),
    )
    op.create_index(op.f("ix_journal_created_at"), "journal", ["created_at"], unique=False)
    op.create_index(op.f("ix_journal_journal_type"), "journal", ["journal_type"], unique=False)
    op.create_index(
        op.f("ix_journal_organization_id"), "journal", ["organization_id"], unique=False
    )
    op.create_table(
        "journal_entry",
        sa.Column("journal_id", sa.UUID(), nullable=False),
        sa.Column("period_id", sa.UUID(), nullable=False),
        sa.Column("entry_number", sa.String(length=50), nullable=True),
        sa.Column("entry_date", sa.Date(), nullable=False),
        sa.Column("narration", sa.Text(), nullable=False),
        sa.Column("reference", sa.String(length=100), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT", "POSTED", "REVERSED", name="entrystatus", native_enum=False, length=20
            ),
            nullable=False,
        ),
        sa.Column("total_debit", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("total_credit", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("posted_by_id", sa.UUID(), nullable=True),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("reversed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reverses_id", sa.UUID(), nullable=True),
        sa.Column("source_type", sa.String(length=50), nullable=True),
        sa.Column("source_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status = 'draft' OR (entry_number IS NOT NULL AND posted_at IS NOT NULL)",
            name=op.f("ck_journal_entry_posted_has_number"),
        ),
        sa.CheckConstraint("total_debit = total_credit", name=op.f("ck_journal_entry_balanced")),
        sa.CheckConstraint(
            "total_debit >= 0 AND total_credit >= 0",
            name=op.f("ck_journal_entry_totals_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["app_user.id"],
            name=op.f("fk_journal_entry_created_by_id_app_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["journal_id"],
            ["journal.id"],
            name=op.f("fk_journal_entry_journal_id_journal"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_journal_entry_organization_id_organization"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["period_id"],
            ["accounting_period.id"],
            name=op.f("fk_journal_entry_period_id_accounting_period"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["posted_by_id"],
            ["app_user.id"],
            name=op.f("fk_journal_entry_posted_by_id_app_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["reverses_id"],
            ["journal_entry.id"],
            name=op.f("fk_journal_entry_reverses_id_journal_entry"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_journal_entry")),
        sa.UniqueConstraint("organization_id", "entry_number", name="uq_entry_org_number"),
    )
    op.create_index(
        "ix_entry_org_date_status",
        "journal_entry",
        ["organization_id", "entry_date", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_journal_entry_created_at"), "journal_entry", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_journal_entry_entry_date"), "journal_entry", ["entry_date"], unique=False
    )
    op.create_index(
        op.f("ix_journal_entry_entry_number"), "journal_entry", ["entry_number"], unique=False
    )
    op.create_index(
        op.f("ix_journal_entry_journal_id"), "journal_entry", ["journal_id"], unique=False
    )
    op.create_index(
        op.f("ix_journal_entry_organization_id"), "journal_entry", ["organization_id"], unique=False
    )
    op.create_index(
        op.f("ix_journal_entry_period_id"), "journal_entry", ["period_id"], unique=False
    )
    op.create_index(
        op.f("ix_journal_entry_reference"), "journal_entry", ["reference"], unique=False
    )
    op.create_index(
        op.f("ix_journal_entry_source_id"), "journal_entry", ["source_id"], unique=False
    )
    op.create_index(
        op.f("ix_journal_entry_source_type"), "journal_entry", ["source_type"], unique=False
    )
    op.create_index(op.f("ix_journal_entry_status"), "journal_entry", ["status"], unique=False)
    op.create_table(
        "journal_entry_line",
        sa.Column("entry_id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("line_number", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("debit", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("credit", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(debit > 0 AND credit = 0) OR (credit > 0 AND debit = 0)",
            name=op.f("ck_journal_entry_line_single_sided"),
        ),
        sa.CheckConstraint(
            "debit >= 0 AND credit >= 0", name=op.f("ck_journal_entry_line_amounts_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
            name=op.f("fk_journal_entry_line_account_id_account"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["entry_id"],
            ["journal_entry.id"],
            name=op.f("fk_journal_entry_line_entry_id_journal_entry"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_journal_entry_line")),
    )
    op.create_index(
        op.f("ix_journal_entry_line_account_id"), "journal_entry_line", ["account_id"], unique=False
    )
    op.create_index(
        op.f("ix_journal_entry_line_created_at"), "journal_entry_line", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_journal_entry_line_entry_id"), "journal_entry_line", ["entry_id"], unique=False
    )
    op.create_index(
        "ix_line_account_entry", "journal_entry_line", ["account_id", "entry_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_line_account_entry", table_name="journal_entry_line")
    op.drop_index(op.f("ix_journal_entry_line_entry_id"), table_name="journal_entry_line")
    op.drop_index(op.f("ix_journal_entry_line_created_at"), table_name="journal_entry_line")
    op.drop_index(op.f("ix_journal_entry_line_account_id"), table_name="journal_entry_line")
    op.drop_table("journal_entry_line")
    op.drop_index(op.f("ix_journal_entry_status"), table_name="journal_entry")
    op.drop_index(op.f("ix_journal_entry_source_type"), table_name="journal_entry")
    op.drop_index(op.f("ix_journal_entry_source_id"), table_name="journal_entry")
    op.drop_index(op.f("ix_journal_entry_reference"), table_name="journal_entry")
    op.drop_index(op.f("ix_journal_entry_period_id"), table_name="journal_entry")
    op.drop_index(op.f("ix_journal_entry_organization_id"), table_name="journal_entry")
    op.drop_index(op.f("ix_journal_entry_journal_id"), table_name="journal_entry")
    op.drop_index(op.f("ix_journal_entry_entry_number"), table_name="journal_entry")
    op.drop_index(op.f("ix_journal_entry_entry_date"), table_name="journal_entry")
    op.drop_index(op.f("ix_journal_entry_created_at"), table_name="journal_entry")
    op.drop_index("ix_entry_org_date_status", table_name="journal_entry")
    op.drop_table("journal_entry")
    op.drop_index(op.f("ix_journal_organization_id"), table_name="journal")
    op.drop_index(op.f("ix_journal_journal_type"), table_name="journal")
    op.drop_index(op.f("ix_journal_created_at"), table_name="journal")
    op.drop_table("journal")
    op.drop_index("ix_period_org_range", table_name="accounting_period")
    op.drop_index(op.f("ix_accounting_period_organization_id"), table_name="accounting_period")
    op.drop_index(op.f("ix_accounting_period_fiscal_year_id"), table_name="accounting_period")
    op.drop_index(op.f("ix_accounting_period_end_date"), table_name="accounting_period")
    op.drop_index(op.f("ix_accounting_period_created_at"), table_name="accounting_period")
    op.drop_table("accounting_period")
    op.drop_index(op.f("ix_number_sequence_organization_id"), table_name="number_sequence")
    op.drop_index(op.f("ix_number_sequence_created_at"), table_name="number_sequence")
    op.drop_table("number_sequence")
    op.drop_index(op.f("ix_fiscal_year_organization_id"), table_name="fiscal_year")
    op.drop_index(op.f("ix_fiscal_year_created_at"), table_name="fiscal_year")
    op.drop_table("fiscal_year")
    op.drop_index(
        "uq_account_org_system_key",
        table_name="account",
        postgresql_where=sa.text("system_key IS NOT NULL"),
    )
    op.drop_index(
        "ix_account_postable",
        table_name="account",
        postgresql_where=sa.text("is_group IS FALSE AND is_active IS TRUE AND deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_account_parent_id"), table_name="account")
    op.drop_index(op.f("ix_account_organization_id"), table_name="account")
    op.drop_index("ix_account_org_type", table_name="account")
    op.drop_index(op.f("ix_account_deleted_at"), table_name="account")
    op.drop_index(op.f("ix_account_created_at"), table_name="account")
    op.drop_index(op.f("ix_account_account_type"), table_name="account")
    op.drop_table("account")
    # ### end Alembic commands ###
