"""purchasing suppliers products warehouses stock purchase orders receipts bills

Revision ID: 867711861952
Revises: 9b90a7cc08bf
Created: 2026-07-29 10:22:27.643063+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "867711861952"
down_revision: str | None = "9b90a7cc08bf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "supplier",
        sa.Column("code", sa.String(length=30), nullable=False),
        sa.Column("name", sa.String(length=250), nullable=False),
        sa.Column("legal_name", sa.String(length=250), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("contact_person", sa.String(length=200), nullable=True),
        sa.Column("gstin", sa.String(length=15), nullable=True),
        sa.Column("pan", sa.String(length=10), nullable=True),
        sa.Column("state_code", sa.String(length=2), nullable=True),
        sa.Column("address_line1", sa.String(length=255), nullable=True),
        sa.Column("address_line2", sa.String(length=255), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("state", sa.String(length=100), nullable=True),
        sa.Column("postal_code", sa.String(length=20), nullable=True),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("payment_terms_days", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("bank_account_name", sa.String(length=200), nullable=True),
        sa.Column("bank_account_number", sa.String(length=50), nullable=True),
        sa.Column("bank_ifsc", sa.String(length=20), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("payment_terms_days >= 0", name=op.f("ck_supplier_terms_non_negative")),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_supplier_organization_id_organization"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_supplier")),
        sa.UniqueConstraint("organization_id", "code", name="uq_supplier_org_code"),
    )
    op.create_index(op.f("ix_supplier_created_at"), "supplier", ["created_at"], unique=False)
    op.create_index(op.f("ix_supplier_deleted_at"), "supplier", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_supplier_email"), "supplier", ["email"], unique=False)
    op.create_index(op.f("ix_supplier_gstin"), "supplier", ["gstin"], unique=False)
    op.create_index(op.f("ix_supplier_name"), "supplier", ["name"], unique=False)
    op.create_index("ix_supplier_org_name", "supplier", ["organization_id", "name"], unique=False)
    op.create_index(
        op.f("ix_supplier_organization_id"), "supplier", ["organization_id"], unique=False
    )
    op.create_table(
        "warehouse",
        sa.Column("code", sa.String(length=30), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("address_line1", sa.String(length=255), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("state", sa.String(length=100), nullable=True),
        sa.Column("postal_code", sa.String(length=20), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_warehouse_organization_id_organization"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_warehouse")),
        sa.UniqueConstraint("organization_id", "code", name="uq_warehouse_org_code"),
    )
    op.create_index(op.f("ix_warehouse_created_at"), "warehouse", ["created_at"], unique=False)
    op.create_index(op.f("ix_warehouse_deleted_at"), "warehouse", ["deleted_at"], unique=False)
    op.create_index(
        op.f("ix_warehouse_organization_id"), "warehouse", ["organization_id"], unique=False
    )
    op.create_index(
        "uq_warehouse_single_default",
        "warehouse",
        ["organization_id"],
        unique=True,
        postgresql_where=sa.text("is_default IS TRUE AND deleted_at IS NULL"),
    )
    op.create_table(
        "product",
        sa.Column("sku", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=250), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("barcode", sa.String(length=50), nullable=True),
        sa.Column(
            "kind",
            sa.Enum(
                "stocked",
                "service",
                "consumable",
                name="productkind",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("hsn_code", sa.String(length=10), nullable=True),
        sa.Column("unit", sa.String(length=20), nullable=False),
        sa.Column("tax_rate", sa.Numeric(precision=9, scale=4), nullable=False),
        sa.Column("sale_price", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("purchase_price", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("reorder_level", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("revenue_account_id", sa.UUID(), nullable=True),
        sa.Column("inventory_account_id", sa.UUID(), nullable=True),
        sa.Column("cogs_account_id", sa.UUID(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("reorder_level >= 0", name=op.f("ck_product_reorder_non_negative")),
        sa.CheckConstraint(
            "sale_price >= 0 AND purchase_price >= 0", name=op.f("ck_product_prices_non_negative")
        ),
        sa.CheckConstraint(
            "tax_rate >= 0 AND tax_rate <= 100", name=op.f("ck_product_tax_rate_range")
        ),
        sa.ForeignKeyConstraint(
            ["cogs_account_id"],
            ["account.id"],
            name=op.f("fk_product_cogs_account_id_account"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["inventory_account_id"],
            ["account.id"],
            name=op.f("fk_product_inventory_account_id_account"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_product_organization_id_organization"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["revenue_account_id"],
            ["account.id"],
            name=op.f("fk_product_revenue_account_id_account"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product")),
        sa.UniqueConstraint("organization_id", "sku", name="uq_product_org_sku"),
    )
    op.create_index(op.f("ix_product_created_at"), "product", ["created_at"], unique=False)
    op.create_index(op.f("ix_product_deleted_at"), "product", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_product_name"), "product", ["name"], unique=False)
    op.create_index(
        "ix_product_org_active", "product", ["organization_id", "is_active"], unique=False
    )
    op.create_index(
        op.f("ix_product_organization_id"), "product", ["organization_id"], unique=False
    )
    op.create_index(
        "uq_product_org_barcode",
        "product",
        ["organization_id", "barcode"],
        unique=True,
        postgresql_where=sa.text("barcode IS NOT NULL AND deleted_at IS NULL"),
    )
    op.create_table(
        "purchase_order",
        sa.Column("order_number", sa.String(length=50), nullable=False),
        sa.Column("supplier_id", sa.UUID(), nullable=False),
        sa.Column("warehouse_id", sa.UUID(), nullable=True),
        sa.Column("order_date", sa.Date(), nullable=False),
        sa.Column("expected_date", sa.Date(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "pending_approval",
                "approved",
                "partially_received",
                "received",
                "cancelled",
                name="purchaseorderstatus",
                native_enum=False,
                create_constraint=True,
                length=25,
            ),
            nullable=False,
        ),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_by_id", sa.UUID(), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("subtotal", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("discount_total", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("taxable_total", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("cgst_total", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("sgst_total", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("igst_total", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("tax_total", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("round_off", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("grand_total", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "tax_treatment",
            sa.Enum(
                "intra_state",
                "inter_state",
                "export",
                "exempt",
                name="taxtreatment",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("terms", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "cgst_total + sgst_total + igst_total = tax_total",
            name=op.f("ck_purchase_order_po_tax_split_reconciles"),
        ),
        sa.CheckConstraint(
            "grand_total >= 0", name=op.f("ck_purchase_order_po_total_non_negative")
        ),
        sa.CheckConstraint(
            "taxable_total + tax_total + round_off = grand_total",
            name=op.f("ck_purchase_order_po_total_reconciles"),
        ),
        sa.ForeignKeyConstraint(
            ["approved_by_id"],
            ["app_user.id"],
            name=op.f("fk_purchase_order_approved_by_id_app_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["app_user.id"],
            name=op.f("fk_purchase_order_created_by_id_app_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_purchase_order_organization_id_organization"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["supplier.id"],
            name=op.f("fk_purchase_order_supplier_id_supplier"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouse.id"],
            name=op.f("fk_purchase_order_warehouse_id_warehouse"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchase_order")),
        sa.UniqueConstraint("organization_id", "order_number", name="uq_po_org_number"),
    )
    op.create_index(
        op.f("ix_purchase_order_created_at"), "purchase_order", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_purchase_order_deleted_at"), "purchase_order", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_purchase_order_order_date"), "purchase_order", ["order_date"], unique=False
    )
    op.create_index(
        op.f("ix_purchase_order_order_number"), "purchase_order", ["order_number"], unique=False
    )
    op.create_index(
        op.f("ix_purchase_order_organization_id"),
        "purchase_order",
        ["organization_id"],
        unique=False,
    )
    op.create_index(op.f("ix_purchase_order_status"), "purchase_order", ["status"], unique=False)
    op.create_index(
        op.f("ix_purchase_order_supplier_id"), "purchase_order", ["supplier_id"], unique=False
    )
    op.create_table(
        "purchase_order_line",
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=True),
        sa.Column("received_quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("line_number", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("hsn_code", sa.String(length=10), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("unit", sa.String(length=20), nullable=True),
        sa.Column("unit_price", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("discount_percent", sa.Numeric(precision=9, scale=4), nullable=False),
        sa.Column("discount_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("tax_rate", sa.Numeric(precision=9, scale=4), nullable=False),
        sa.Column("cgst_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("sgst_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("igst_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("gross_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("taxable_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("tax_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("line_total", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "cgst_amount + sgst_amount + igst_amount = tax_amount",
            name=op.f("ck_purchase_order_line_po_line_tax_split_reconciles"),
        ),
        sa.CheckConstraint(
            "quantity > 0", name=op.f("ck_purchase_order_line_po_line_quantity_positive")
        ),
        sa.CheckConstraint(
            "received_quantity >= 0",
            name=op.f("ck_purchase_order_line_po_line_received_non_negative"),
        ),
        sa.CheckConstraint(
            "tax_rate >= 0 AND tax_rate <= 100",
            name=op.f("ck_purchase_order_line_po_line_tax_rate_range"),
        ),
        sa.CheckConstraint(
            "taxable_amount + tax_amount = line_total",
            name=op.f("ck_purchase_order_line_po_line_total_reconciles"),
        ),
        sa.CheckConstraint(
            "unit_price >= 0", name=op.f("ck_purchase_order_line_po_line_price_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["purchase_order.id"],
            name=op.f("fk_purchase_order_line_order_id_purchase_order"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
            name=op.f("fk_purchase_order_line_product_id_product"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchase_order_line")),
    )
    op.create_index(
        op.f("ix_purchase_order_line_created_at"),
        "purchase_order_line",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_purchase_order_line_order_id"), "purchase_order_line", ["order_id"], unique=False
    )
    op.create_index(
        op.f("ix_purchase_order_line_product_id"),
        "purchase_order_line",
        ["product_id"],
        unique=False,
    )
    op.create_table(
        "stock_level",
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("warehouse_id", sa.UUID(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("average_cost", sa.Numeric(), nullable=False),
        sa.Column("reserved_quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("last_movement_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("average_cost >= 0", name=op.f("ck_stock_level_cost_non_negative")),
        sa.CheckConstraint("quantity >= 0", name=op.f("ck_stock_level_quantity_non_negative")),
        sa.CheckConstraint(
            "reserved_quantity >= 0", name=op.f("ck_stock_level_reserved_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_stock_level_organization_id_organization"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
            name=op.f("fk_stock_level_product_id_product"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouse.id"],
            name=op.f("fk_stock_level_warehouse_id_warehouse"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_level")),
        sa.UniqueConstraint("product_id", "warehouse_id", name="uq_stock_product_warehouse"),
    )
    op.create_index(op.f("ix_stock_level_created_at"), "stock_level", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_stock_level_organization_id"), "stock_level", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_stock_level_product_id"), "stock_level", ["product_id"], unique=False)
    op.create_index(
        op.f("ix_stock_level_warehouse_id"), "stock_level", ["warehouse_id"], unique=False
    )
    op.create_table(
        "goods_receipt",
        sa.Column("receipt_number", sa.String(length=50), nullable=False),
        sa.Column("supplier_id", sa.UUID(), nullable=False),
        sa.Column("purchase_order_id", sa.UUID(), nullable=True),
        sa.Column("warehouse_id", sa.UUID(), nullable=False),
        sa.Column("receipt_date", sa.Date(), nullable=False),
        sa.Column("supplier_reference", sa.String(length=100), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "posted",
                "cancelled",
                name="goodsreceiptstatus",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("total_cost", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("journal_entry_id", sa.UUID(), nullable=True),
        sa.Column("reversal_entry_id", sa.UUID(), nullable=True),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(status = 'draft' AND journal_entry_id IS NULL) OR status <> 'draft'",
            name=op.f("ck_goods_receipt_grn_draft_has_no_entry"),
        ),
        sa.CheckConstraint("total_cost >= 0", name=op.f("ck_goods_receipt_grn_cost_non_negative")),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["app_user.id"],
            name=op.f("fk_goods_receipt_created_by_id_app_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["journal_entry_id"],
            ["journal_entry.id"],
            name=op.f("fk_goods_receipt_journal_entry_id_journal_entry"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_goods_receipt_organization_id_organization"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["purchase_order_id"],
            ["purchase_order.id"],
            name=op.f("fk_goods_receipt_purchase_order_id_purchase_order"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["reversal_entry_id"],
            ["journal_entry.id"],
            name=op.f("fk_goods_receipt_reversal_entry_id_journal_entry"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["supplier.id"],
            name=op.f("fk_goods_receipt_supplier_id_supplier"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouse.id"],
            name=op.f("fk_goods_receipt_warehouse_id_warehouse"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_goods_receipt")),
        sa.UniqueConstraint("organization_id", "receipt_number", name="uq_grn_org_number"),
    )
    op.create_index(
        op.f("ix_goods_receipt_created_at"), "goods_receipt", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_goods_receipt_deleted_at"), "goods_receipt", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_goods_receipt_organization_id"), "goods_receipt", ["organization_id"], unique=False
    )
    op.create_index(
        op.f("ix_goods_receipt_purchase_order_id"),
        "goods_receipt",
        ["purchase_order_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_goods_receipt_receipt_date"), "goods_receipt", ["receipt_date"], unique=False
    )
    op.create_index(
        op.f("ix_goods_receipt_receipt_number"), "goods_receipt", ["receipt_number"], unique=False
    )
    op.create_index(op.f("ix_goods_receipt_status"), "goods_receipt", ["status"], unique=False)
    op.create_index(
        op.f("ix_goods_receipt_supplier_id"), "goods_receipt", ["supplier_id"], unique=False
    )
    op.create_table(
        "stock_movement",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("warehouse_id", sa.UUID(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "receipt",
                "issue",
                "adjustment",
                "transfer_out",
                "transfer_in",
                "return_out",
                "return_in",
                "reversal",
                name="movementkind",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("movement_date", sa.Date(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("unit_cost", sa.Numeric(), nullable=False),
        sa.Column("total_cost", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("balance_after", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("average_cost_after", sa.Numeric(), nullable=False),
        sa.Column("source_type", sa.String(length=50), nullable=True),
        sa.Column("source_id", sa.UUID(), nullable=True),
        sa.Column("reference", sa.String(length=100), nullable=True),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column("journal_entry_id", sa.UUID(), nullable=True),
        sa.Column("reverses_id", sa.UUID(), nullable=True),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "balance_after >= 0", name=op.f("ck_stock_movement_balance_non_negative")
        ),
        sa.CheckConstraint("quantity <> 0", name=op.f("ck_stock_movement_quantity_non_zero")),
        sa.CheckConstraint("unit_cost >= 0", name=op.f("ck_stock_movement_unit_cost_non_negative")),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["app_user.id"],
            name=op.f("fk_stock_movement_created_by_id_app_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["journal_entry_id"],
            ["journal_entry.id"],
            name=op.f("fk_stock_movement_journal_entry_id_journal_entry"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_stock_movement_organization_id_organization"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
            name=op.f("fk_stock_movement_product_id_product"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reverses_id"],
            ["stock_movement.id"],
            name=op.f("fk_stock_movement_reverses_id_stock_movement"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouse.id"],
            name=op.f("fk_stock_movement_warehouse_id_warehouse"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_movement")),
    )
    op.create_index(
        "ix_movement_org_date", "stock_movement", ["organization_id", "movement_date"], unique=False
    )
    op.create_index(
        "ix_movement_product_warehouse_date",
        "stock_movement",
        ["product_id", "warehouse_id", "movement_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_movement_created_at"), "stock_movement", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_stock_movement_kind"), "stock_movement", ["kind"], unique=False)
    op.create_index(
        op.f("ix_stock_movement_movement_date"), "stock_movement", ["movement_date"], unique=False
    )
    op.create_index(
        op.f("ix_stock_movement_organization_id"),
        "stock_movement",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_movement_product_id"), "stock_movement", ["product_id"], unique=False
    )
    op.create_index(
        op.f("ix_stock_movement_source_id"), "stock_movement", ["source_id"], unique=False
    )
    op.create_index(
        op.f("ix_stock_movement_source_type"), "stock_movement", ["source_type"], unique=False
    )
    op.create_index(
        op.f("ix_stock_movement_warehouse_id"), "stock_movement", ["warehouse_id"], unique=False
    )
    op.create_table(
        "supplier_payment",
        sa.Column("payment_number", sa.String(length=50), nullable=False),
        sa.Column("supplier_id", sa.UUID(), nullable=False),
        sa.Column("payment_date", sa.Date(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("unallocated_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("method", sa.String(length=20), nullable=False),
        sa.Column("reference", sa.String(length=100), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("source_account_id", sa.UUID(), nullable=True),
        sa.Column("journal_entry_id", sa.UUID(), nullable=True),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("amount > 0", name=op.f("ck_supplier_payment_sp_amount_positive")),
        sa.CheckConstraint(
            "unallocated_amount >= 0 AND unallocated_amount <= amount",
            name=op.f("ck_supplier_payment_sp_unallocated_within_amount"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["app_user.id"],
            name=op.f("fk_supplier_payment_created_by_id_app_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["journal_entry_id"],
            ["journal_entry.id"],
            name=op.f("fk_supplier_payment_journal_entry_id_journal_entry"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_supplier_payment_organization_id_organization"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_account_id"],
            ["account.id"],
            name=op.f("fk_supplier_payment_source_account_id_account"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["supplier.id"],
            name=op.f("fk_supplier_payment_supplier_id_supplier"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_supplier_payment")),
        sa.UniqueConstraint(
            "organization_id", "payment_number", name="uq_supplier_payment_org_number"
        ),
    )
    op.create_index(
        op.f("ix_supplier_payment_created_at"), "supplier_payment", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_supplier_payment_deleted_at"), "supplier_payment", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_supplier_payment_organization_id"),
        "supplier_payment",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_supplier_payment_payment_date"), "supplier_payment", ["payment_date"], unique=False
    )
    op.create_index(
        op.f("ix_supplier_payment_payment_number"),
        "supplier_payment",
        ["payment_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_supplier_payment_supplier_id"), "supplier_payment", ["supplier_id"], unique=False
    )
    op.create_table(
        "bill",
        sa.Column("bill_number", sa.String(length=50), nullable=False),
        sa.Column("supplier_invoice_number", sa.String(length=100), nullable=True),
        sa.Column("supplier_id", sa.UUID(), nullable=False),
        sa.Column("purchase_order_id", sa.UUID(), nullable=True),
        sa.Column("goods_receipt_id", sa.UUID(), nullable=True),
        sa.Column("bill_date", sa.Date(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "posted",
                "partially_paid",
                "paid",
                "cancelled",
                name="billstatus",
                native_enum=False,
                create_constraint=True,
                length=25,
            ),
            nullable=False,
        ),
        sa.Column("paid_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("supplier_gstin", sa.String(length=15), nullable=True),
        sa.Column("journal_entry_id", sa.UUID(), nullable=True),
        sa.Column("reversal_entry_id", sa.UUID(), nullable=True),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("subtotal", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("discount_total", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("taxable_total", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("cgst_total", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("sgst_total", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("igst_total", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("tax_total", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("round_off", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("grand_total", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "tax_treatment",
            sa.Enum(
                "intra_state",
                "inter_state",
                "export",
                "exempt",
                name="taxtreatment",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("terms", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "cgst_total + sgst_total + igst_total = tax_total",
            name=op.f("ck_bill_bill_tax_split_reconciles"),
        ),
        sa.CheckConstraint("due_date >= bill_date", name=op.f("ck_bill_bill_due_after_issue")),
        sa.CheckConstraint("grand_total >= 0", name=op.f("ck_bill_bill_total_non_negative")),
        sa.CheckConstraint(
            "paid_amount <= grand_total", name=op.f("ck_bill_bill_paid_within_total")
        ),
        sa.CheckConstraint("paid_amount >= 0", name=op.f("ck_bill_bill_paid_non_negative")),
        sa.CheckConstraint(
            "taxable_total + tax_total + round_off = grand_total",
            name=op.f("ck_bill_bill_total_reconciles"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["app_user.id"],
            name=op.f("fk_bill_created_by_id_app_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["goods_receipt_id"],
            ["goods_receipt.id"],
            name=op.f("fk_bill_goods_receipt_id_goods_receipt"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["journal_entry_id"],
            ["journal_entry.id"],
            name=op.f("fk_bill_journal_entry_id_journal_entry"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_bill_organization_id_organization"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["purchase_order_id"],
            ["purchase_order.id"],
            name=op.f("fk_bill_purchase_order_id_purchase_order"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["reversal_entry_id"],
            ["journal_entry.id"],
            name=op.f("fk_bill_reversal_entry_id_journal_entry"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["supplier.id"],
            name=op.f("fk_bill_supplier_id_supplier"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bill")),
        sa.UniqueConstraint("organization_id", "bill_number", name="uq_bill_org_number"),
    )
    op.create_index(op.f("ix_bill_bill_date"), "bill", ["bill_date"], unique=False)
    op.create_index(op.f("ix_bill_bill_number"), "bill", ["bill_number"], unique=False)
    op.create_index(op.f("ix_bill_created_at"), "bill", ["created_at"], unique=False)
    op.create_index(op.f("ix_bill_deleted_at"), "bill", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_bill_due_date"), "bill", ["due_date"], unique=False)
    op.create_index(
        "ix_bill_org_status_due", "bill", ["organization_id", "status", "due_date"], unique=False
    )
    op.create_index(op.f("ix_bill_organization_id"), "bill", ["organization_id"], unique=False)
    op.create_index(op.f("ix_bill_status"), "bill", ["status"], unique=False)
    op.create_index(op.f("ix_bill_supplier_id"), "bill", ["supplier_id"], unique=False)
    op.create_index(
        op.f("ix_bill_supplier_invoice_number"), "bill", ["supplier_invoice_number"], unique=False
    )
    op.create_index(
        "uq_bill_supplier_invoice",
        "bill",
        ["organization_id", "supplier_id", "supplier_invoice_number"],
        unique=True,
        postgresql_where=sa.text("supplier_invoice_number IS NOT NULL AND deleted_at IS NULL"),
    )
    op.create_table(
        "goods_receipt_line",
        sa.Column("receipt_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("purchase_order_line_id", sa.UUID(), nullable=True),
        sa.Column("line_number", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("unit_cost", sa.Numeric(), nullable=False),
        sa.Column("total_cost", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("rejected_quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "quantity > 0", name=op.f("ck_goods_receipt_line_grn_line_quantity_positive")
        ),
        sa.CheckConstraint(
            "rejected_quantity >= 0 AND rejected_quantity <= quantity",
            name=op.f("ck_goods_receipt_line_grn_line_rejected_within_quantity"),
        ),
        sa.CheckConstraint(
            "unit_cost >= 0", name=op.f("ck_goods_receipt_line_grn_line_cost_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
            name=op.f("fk_goods_receipt_line_product_id_product"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["purchase_order_line_id"],
            ["purchase_order_line.id"],
            name=op.f("fk_goods_receipt_line_purchase_order_line_id_purchase_order_line"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["receipt_id"],
            ["goods_receipt.id"],
            name=op.f("fk_goods_receipt_line_receipt_id_goods_receipt"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_goods_receipt_line")),
    )
    op.create_index(
        op.f("ix_goods_receipt_line_created_at"), "goods_receipt_line", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_goods_receipt_line_product_id"), "goods_receipt_line", ["product_id"], unique=False
    )
    op.create_index(
        op.f("ix_goods_receipt_line_receipt_id"), "goods_receipt_line", ["receipt_id"], unique=False
    )
    op.create_table(
        "bill_line",
        sa.Column("bill_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=True),
        sa.Column("expense_account_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("line_number", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("hsn_code", sa.String(length=10), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("unit", sa.String(length=20), nullable=True),
        sa.Column("unit_price", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("discount_percent", sa.Numeric(precision=9, scale=4), nullable=False),
        sa.Column("discount_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("tax_rate", sa.Numeric(precision=9, scale=4), nullable=False),
        sa.Column("cgst_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("sgst_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("igst_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("gross_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("taxable_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("tax_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("line_total", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "cgst_amount + sgst_amount + igst_amount = tax_amount",
            name=op.f("ck_bill_line_bill_line_tax_split_reconciles"),
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_bill_line_bill_line_quantity_positive")),
        sa.CheckConstraint(
            "tax_rate >= 0 AND tax_rate <= 100", name=op.f("ck_bill_line_bill_line_tax_rate_range")
        ),
        sa.CheckConstraint(
            "taxable_amount + tax_amount = line_total",
            name=op.f("ck_bill_line_bill_line_total_reconciles"),
        ),
        sa.CheckConstraint(
            "unit_price >= 0", name=op.f("ck_bill_line_bill_line_price_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["bill_id"], ["bill.id"], name=op.f("fk_bill_line_bill_id_bill"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["expense_account_id"],
            ["account.id"],
            name=op.f("fk_bill_line_expense_account_id_account"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
            name=op.f("fk_bill_line_product_id_product"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bill_line")),
    )
    op.create_index(op.f("ix_bill_line_bill_id"), "bill_line", ["bill_id"], unique=False)
    op.create_index(op.f("ix_bill_line_created_at"), "bill_line", ["created_at"], unique=False)
    op.create_index(op.f("ix_bill_line_product_id"), "bill_line", ["product_id"], unique=False)
    op.create_table(
        "supplier_payment_allocation",
        sa.Column("payment_id", sa.UUID(), nullable=False),
        sa.Column("bill_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "amount > 0", name=op.f("ck_supplier_payment_allocation_sp_allocation_amount_positive")
        ),
        sa.ForeignKeyConstraint(
            ["bill_id"],
            ["bill.id"],
            name=op.f("fk_supplier_payment_allocation_bill_id_bill"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["payment_id"],
            ["supplier_payment.id"],
            name=op.f("fk_supplier_payment_allocation_payment_id_supplier_payment"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_supplier_payment_allocation")),
        sa.UniqueConstraint("payment_id", "bill_id", name="uq_sp_allocation_payment_bill"),
    )
    op.create_index(
        op.f("ix_supplier_payment_allocation_bill_id"),
        "supplier_payment_allocation",
        ["bill_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_supplier_payment_allocation_created_at"),
        "supplier_payment_allocation",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_supplier_payment_allocation_payment_id"),
        "supplier_payment_allocation",
        ["payment_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_supplier_payment_allocation_payment_id"), table_name="supplier_payment_allocation"
    )
    op.drop_index(
        op.f("ix_supplier_payment_allocation_created_at"), table_name="supplier_payment_allocation"
    )
    op.drop_index(
        op.f("ix_supplier_payment_allocation_bill_id"), table_name="supplier_payment_allocation"
    )
    op.drop_table("supplier_payment_allocation")
    op.drop_index(op.f("ix_bill_line_product_id"), table_name="bill_line")
    op.drop_index(op.f("ix_bill_line_created_at"), table_name="bill_line")
    op.drop_index(op.f("ix_bill_line_bill_id"), table_name="bill_line")
    op.drop_table("bill_line")
    op.drop_index(op.f("ix_goods_receipt_line_receipt_id"), table_name="goods_receipt_line")
    op.drop_index(op.f("ix_goods_receipt_line_product_id"), table_name="goods_receipt_line")
    op.drop_index(op.f("ix_goods_receipt_line_created_at"), table_name="goods_receipt_line")
    op.drop_table("goods_receipt_line")
    op.drop_index(
        "uq_bill_supplier_invoice",
        table_name="bill",
        postgresql_where=sa.text("supplier_invoice_number IS NOT NULL AND deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_bill_supplier_invoice_number"), table_name="bill")
    op.drop_index(op.f("ix_bill_supplier_id"), table_name="bill")
    op.drop_index(op.f("ix_bill_status"), table_name="bill")
    op.drop_index(op.f("ix_bill_organization_id"), table_name="bill")
    op.drop_index("ix_bill_org_status_due", table_name="bill")
    op.drop_index(op.f("ix_bill_due_date"), table_name="bill")
    op.drop_index(op.f("ix_bill_deleted_at"), table_name="bill")
    op.drop_index(op.f("ix_bill_created_at"), table_name="bill")
    op.drop_index(op.f("ix_bill_bill_number"), table_name="bill")
    op.drop_index(op.f("ix_bill_bill_date"), table_name="bill")
    op.drop_table("bill")
    op.drop_index(op.f("ix_supplier_payment_supplier_id"), table_name="supplier_payment")
    op.drop_index(op.f("ix_supplier_payment_payment_number"), table_name="supplier_payment")
    op.drop_index(op.f("ix_supplier_payment_payment_date"), table_name="supplier_payment")
    op.drop_index(op.f("ix_supplier_payment_organization_id"), table_name="supplier_payment")
    op.drop_index(op.f("ix_supplier_payment_deleted_at"), table_name="supplier_payment")
    op.drop_index(op.f("ix_supplier_payment_created_at"), table_name="supplier_payment")
    op.drop_table("supplier_payment")
    op.drop_index(op.f("ix_stock_movement_warehouse_id"), table_name="stock_movement")
    op.drop_index(op.f("ix_stock_movement_source_type"), table_name="stock_movement")
    op.drop_index(op.f("ix_stock_movement_source_id"), table_name="stock_movement")
    op.drop_index(op.f("ix_stock_movement_product_id"), table_name="stock_movement")
    op.drop_index(op.f("ix_stock_movement_organization_id"), table_name="stock_movement")
    op.drop_index(op.f("ix_stock_movement_movement_date"), table_name="stock_movement")
    op.drop_index(op.f("ix_stock_movement_kind"), table_name="stock_movement")
    op.drop_index(op.f("ix_stock_movement_created_at"), table_name="stock_movement")
    op.drop_index("ix_movement_product_warehouse_date", table_name="stock_movement")
    op.drop_index("ix_movement_org_date", table_name="stock_movement")
    op.drop_table("stock_movement")
    op.drop_index(op.f("ix_goods_receipt_supplier_id"), table_name="goods_receipt")
    op.drop_index(op.f("ix_goods_receipt_status"), table_name="goods_receipt")
    op.drop_index(op.f("ix_goods_receipt_receipt_number"), table_name="goods_receipt")
    op.drop_index(op.f("ix_goods_receipt_receipt_date"), table_name="goods_receipt")
    op.drop_index(op.f("ix_goods_receipt_purchase_order_id"), table_name="goods_receipt")
    op.drop_index(op.f("ix_goods_receipt_organization_id"), table_name="goods_receipt")
    op.drop_index(op.f("ix_goods_receipt_deleted_at"), table_name="goods_receipt")
    op.drop_index(op.f("ix_goods_receipt_created_at"), table_name="goods_receipt")
    op.drop_table("goods_receipt")
    op.drop_index(op.f("ix_stock_level_warehouse_id"), table_name="stock_level")
    op.drop_index(op.f("ix_stock_level_product_id"), table_name="stock_level")
    op.drop_index(op.f("ix_stock_level_organization_id"), table_name="stock_level")
    op.drop_index(op.f("ix_stock_level_created_at"), table_name="stock_level")
    op.drop_table("stock_level")
    op.drop_index(op.f("ix_purchase_order_line_product_id"), table_name="purchase_order_line")
    op.drop_index(op.f("ix_purchase_order_line_order_id"), table_name="purchase_order_line")
    op.drop_index(op.f("ix_purchase_order_line_created_at"), table_name="purchase_order_line")
    op.drop_table("purchase_order_line")
    op.drop_index(op.f("ix_purchase_order_supplier_id"), table_name="purchase_order")
    op.drop_index(op.f("ix_purchase_order_status"), table_name="purchase_order")
    op.drop_index(op.f("ix_purchase_order_organization_id"), table_name="purchase_order")
    op.drop_index(op.f("ix_purchase_order_order_number"), table_name="purchase_order")
    op.drop_index(op.f("ix_purchase_order_order_date"), table_name="purchase_order")
    op.drop_index(op.f("ix_purchase_order_deleted_at"), table_name="purchase_order")
    op.drop_index(op.f("ix_purchase_order_created_at"), table_name="purchase_order")
    op.drop_table("purchase_order")
    op.drop_index(
        "uq_product_org_barcode",
        table_name="product",
        postgresql_where=sa.text("barcode IS NOT NULL AND deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_product_organization_id"), table_name="product")
    op.drop_index("ix_product_org_active", table_name="product")
    op.drop_index(op.f("ix_product_name"), table_name="product")
    op.drop_index(op.f("ix_product_deleted_at"), table_name="product")
    op.drop_index(op.f("ix_product_created_at"), table_name="product")
    op.drop_table("product")
    op.drop_index(
        "uq_warehouse_single_default",
        table_name="warehouse",
        postgresql_where=sa.text("is_default IS TRUE AND deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_warehouse_organization_id"), table_name="warehouse")
    op.drop_index(op.f("ix_warehouse_deleted_at"), table_name="warehouse")
    op.drop_index(op.f("ix_warehouse_created_at"), table_name="warehouse")
    op.drop_table("warehouse")
    op.drop_index(op.f("ix_supplier_organization_id"), table_name="supplier")
    op.drop_index("ix_supplier_org_name", table_name="supplier")
    op.drop_index(op.f("ix_supplier_name"), table_name="supplier")
    op.drop_index(op.f("ix_supplier_gstin"), table_name="supplier")
    op.drop_index(op.f("ix_supplier_email"), table_name="supplier")
    op.drop_index(op.f("ix_supplier_deleted_at"), table_name="supplier")
    op.drop_index(op.f("ix_supplier_created_at"), table_name="supplier")
    op.drop_table("supplier")
    # ### end Alembic commands ###
