"""bank account details and card holder name

Adds the facts a person needs about an account and the ledger has no use for: which bank,
whose name, and which number.

**`account_number_encrypted` holds a Fernet ciphertext, never a readable number** - the
same treatment as `app_user.totp_secret`. `account_number_last4` is the tail in the clear,
so a list can show "··4321" without decrypting a row per line.

Note the deliberate contrast with the previous revision, which added `payment_card` with
**no** column for a card number at all. A bank account number is stored in full because it
is what you quote to be paid and match against a statement, so discarding it would stop the
software doing its job; a card number has no remaining use once the last four digits are
known, and keeping one would bring this database into PCI DSS scope. Different answers, and
each is the right one for its field.

`payment_card.holder_name` is in the clear. PCI DSS permits retaining a cardholder name -
it is the PAN and the authentication data (CVV, PIN, stripe) that may not be kept - and a
name on its own cannot be used to transact.

`ondelete="CASCADE"` on `account_id` here, where `payment_card` uses `RESTRICT`: this row
describes an account rather than recording something that happened, so if the account can be
deleted at all, its description should go with it.

Revision ID: 2dde7dff2c8d
Revises: b8969303cd3f
Created: 2026-08-02 19:27:11.206243+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "2dde7dff2c8d"
down_revision: str | None = "b8969303cd3f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bank_account_detail",
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("bank_name", sa.String(length=120), nullable=True),
        sa.Column("holder_name", sa.String(length=120), nullable=True),
        sa.Column("account_number_encrypted", sa.String(length=500), nullable=True),
        sa.Column("account_number_last4", sa.String(length=4), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
            name=op.f("fk_bank_account_detail_account_id_account"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_bank_account_detail_organization_id_organization"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bank_account_detail")),
        sa.UniqueConstraint("account_id", name="uq_bank_account_detail_account"),
    )
    op.create_index(
        op.f("ix_bank_account_detail_account_id"),
        "bank_account_detail",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_bank_account_detail_created_at"),
        "bank_account_detail",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_bank_account_detail_organization_id"),
        "bank_account_detail",
        ["organization_id"],
        unique=False,
    )
    op.add_column("payment_card", sa.Column("holder_name", sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("payment_card", "holder_name")
    op.drop_index(op.f("ix_bank_account_detail_organization_id"), table_name="bank_account_detail")
    op.drop_index(op.f("ix_bank_account_detail_created_at"), table_name="bank_account_detail")
    op.drop_index(op.f("ix_bank_account_detail_account_id"), table_name="bank_account_detail")
    op.drop_table("bank_account_detail")
    # ### end Alembic commands ###
