"""Payment cards, so a movement can say which card it went on.

**There is no column for a card number, and that is the point of reviewing this file.**
The table holds a label, the scheme, and four digits - nothing that could be a Primary
Account Number. Storing one would put this entire database inside PCI DSS scope, and the
last four digits are what a card receipt and a bank statement both print anyway. See
``app/modules/billing/models.py`` for the reasoning and ``app/modules/billing/cards.py``
for the one function that ever holds a full number.

``account_id`` is what ties a card to the ledger, and it means two different things by
design:

* A **credit card** owns a liability account created alongside it, under Current
  Liabilities. Spending on one is a debt to the issuer, not a payment, so filing it as a
  cash-equivalent asset would inflate cash and understate what is owed.
* A **debit card** points at a bank account that already existed. It gets no account of
  its own, because a second one would double-count the same money.

``ondelete="RESTRICT"`` on that FK rather than ``CASCADE``: an account with postings
against it is not deletable anyway, and silently dropping a card would lose the record of
which card an entry was made on.

Revision ID: b8969303cd3f
Revises: b7c4e19d2a83
Created: 2026-08-02 17:39:01.221760+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "b8969303cd3f"
down_revision: str | None = "b7c4e19d2a83"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payment_card",
        sa.Column("label", sa.String(length=80), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "credit",
                "debit",
                name="cardkind",
                native_enum=False,
                create_constraint=True,
                length=10,
            ),
            nullable=False,
        ),
        sa.Column(
            "network",
            sa.Enum(
                "visa",
                "mastercard",
                "rupay",
                "amex",
                "discover",
                "diners",
                "jcb",
                "maestro",
                "other",
                name="cardnetwork",
                native_enum=False,
                create_constraint=True,
                length=12,
            ),
            nullable=False,
        ),
        sa.Column("last4", sa.String(length=4), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
            name=op.f("fk_payment_card_account_id_account"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_payment_card_organization_id_organization"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment_card")),
        sa.UniqueConstraint(
            "organization_id",
            "network",
            "last4",
            "kind",
            name="uq_payment_card_org_network_last4_kind",
        ),
    )
    op.create_index(
        op.f("ix_payment_card_account_id"), "payment_card", ["account_id"], unique=False
    )
    op.create_index(
        op.f("ix_payment_card_created_at"), "payment_card", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_payment_card_organization_id"), "payment_card", ["organization_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_payment_card_organization_id"), table_name="payment_card")
    op.drop_index(op.f("ix_payment_card_created_at"), table_name="payment_card")
    op.drop_index(op.f("ix_payment_card_account_id"), table_name="payment_card")
    op.drop_table("payment_card")
    # ### end Alembic commands ###
