"""initial schema users organizations rbac sessions audit

Revision ID: 90cd63df7440
Revises:
Created: 2026-07-26 09:20:02.670594+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "90cd63df7440"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_user",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("avatar_url", sa.String(length=500), nullable=True),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("password_changed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("must_change_password", sa.Boolean(), nullable=False),
        sa.Column("totp_secret", sa.String(length=500), nullable=True),
        sa.Column("totp_enabled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "recovery_code_hashes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("locale", sa.String(length=10), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("theme", sa.String(length=10), nullable=False),
        sa.Column("last_organization_id", sa.UUID(), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app_user")),
    )
    op.create_index(
        "ix_app_user_active",
        "app_user",
        ["is_active"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(op.f("ix_app_user_created_at"), "app_user", ["created_at"], unique=False)
    op.create_index(op.f("ix_app_user_deleted_at"), "app_user", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_app_user_email"), "app_user", ["email"], unique=True)
    op.create_index(
        op.f("ix_app_user_last_organization_id"), "app_user", ["last_organization_id"], unique=False
    )
    op.create_table(
        "organization",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("legal_name", sa.String(length=250), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("website", sa.String(length=255), nullable=True),
        sa.Column("logo_url", sa.String(length=500), nullable=True),
        sa.Column("address_line1", sa.String(length=255), nullable=True),
        sa.Column("address_line2", sa.String(length=255), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("state", sa.String(length=100), nullable=True),
        sa.Column("postal_code", sa.String(length=20), nullable=True),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("fiscal_year_start_month", sa.Integer(), nullable=False),
        sa.Column("gstin", sa.String(length=15), nullable=True),
        sa.Column("pan", sa.String(length=10), nullable=True),
        sa.Column("cin", sa.String(length=21), nullable=True),
        sa.Column(
            "plan",
            sa.Enum(
                "FREE",
                "STARTER",
                "GROWTH",
                "ENTERPRISE",
                name="organizationplan",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("onboarded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "settings",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organization")),
    )
    op.create_index(
        "ix_organization_active",
        "organization",
        ["is_active"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        op.f("ix_organization_created_at"), "organization", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_organization_deleted_at"), "organization", ["deleted_at"], unique=False
    )
    op.create_index(op.f("ix_organization_gstin"), "organization", ["gstin"], unique=False)
    op.create_index(op.f("ix_organization_slug"), "organization", ["slug"], unique=True)
    op.create_table(
        "audit_log",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "action",
            sa.Enum(
                "USER_REGISTERED",
                "USER_LOGGED_IN",
                "USER_LOGIN_FAILED",
                "USER_LOGGED_OUT",
                "USER_EMAIL_VERIFIED",
                "USER_PASSWORD_CHANGED",
                "USER_PASSWORD_RESET_REQUESTED",
                "USER_PASSWORD_RESET_COMPLETED",
                "USER_MAGIC_LINK_REQUESTED",
                "USER_OTP_REQUESTED",
                "USER_LOCKED_OUT",
                "TWO_FACTOR_ENABLED",
                "TWO_FACTOR_DISABLED",
                "TWO_FACTOR_CHALLENGE_FAILED",
                "TWO_FACTOR_RECOVERY_CODE_USED",
                "TWO_FACTOR_RECOVERY_CODES_REGENERATED",
                "SESSION_REVOKED",
                "SESSION_ALL_REVOKED",
                "SESSION_REUSE_DETECTED",
                "USER_PROFILE_UPDATED",
                "ORG_CREATED",
                "ORG_UPDATED",
                "ORG_DELETED",
                "ORG_SWITCHED",
                "MEMBER_INVITED",
                "MEMBER_INVITE_RESENT",
                "MEMBER_INVITE_REVOKED",
                "MEMBER_JOINED",
                "MEMBER_ROLE_CHANGED",
                "MEMBER_SUSPENDED",
                "MEMBER_REACTIVATED",
                "MEMBER_REMOVED",
                "ROLE_CREATED",
                "ROLE_UPDATED",
                "ROLE_DELETED",
                "SETTINGS_UPDATED",
                name="auditaction",
                native_enum=False,
                length=60,
            ),
            nullable=False,
        ),
        sa.Column(
            "severity",
            sa.Enum(
                "INFO", "WARNING", "CRITICAL", name="auditseverity", native_enum=False, length=20
            ),
            nullable=False,
        ),
        sa.Column("summary", sa.String(length=500), nullable=True),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("actor_email", sa.String(length=320), nullable=True),
        sa.Column("actor_label", sa.String(length=200), nullable=True),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("resource_type", sa.String(length=60), nullable=True),
        sa.Column("resource_id", sa.String(length=100), nullable=True),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column(
            "changes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "context",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["app_user.id"],
            name=op.f("fk_audit_log_actor_user_id_app_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_audit_log_organization_id_organization"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index(op.f("ix_audit_log_action"), "audit_log", ["action"], unique=False)
    op.create_index(
        "ix_audit_log_actor_created", "audit_log", ["actor_user_id", "created_at"], unique=False
    )
    op.create_index(
        op.f("ix_audit_log_actor_user_id"), "audit_log", ["actor_user_id"], unique=False
    )
    op.create_index(op.f("ix_audit_log_created_at"), "audit_log", ["created_at"], unique=False)
    op.create_index(
        "ix_audit_log_org_created", "audit_log", ["organization_id", "created_at"], unique=False
    )
    op.create_index(
        op.f("ix_audit_log_organization_id"), "audit_log", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_audit_log_request_id"), "audit_log", ["request_id"], unique=False)
    op.create_index(
        "ix_audit_log_resource",
        "audit_log",
        ["resource_type", "resource_id", "created_at"],
        unique=False,
    )
    op.create_index(op.f("ix_audit_log_resource_id"), "audit_log", ["resource_id"], unique=False)
    op.create_index(
        op.f("ix_audit_log_resource_type"), "audit_log", ["resource_type"], unique=False
    )
    op.create_table(
        "role",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "permissions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_role_organization_id_organization"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_role")),
        sa.UniqueConstraint("organization_id", "slug", name="uq_role_org_slug"),
    )
    op.create_index(op.f("ix_role_created_at"), "role", ["created_at"], unique=False)
    op.create_index(op.f("ix_role_organization_id"), "role", ["organization_id"], unique=False)
    op.create_index(
        "uq_role_single_default",
        "role",
        ["organization_id"],
        unique=True,
        postgresql_where=sa.text("is_default IS TRUE"),
    )
    op.create_table(
        "user_session",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("refresh_token_hash", sa.String(length=64), nullable=False),
        sa.Column("rotated_to_id", sa.UUID(), nullable=True),
        sa.Column("generation", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("device_label", sa.String(length=120), nullable=True),
        sa.Column("device_type", sa.String(length=20), nullable=True),
        sa.Column(
            "login_method",
            sa.Enum(
                "PASSWORD",
                "MAGIC_LINK",
                "OTP",
                "INVITATION",
                "IMPERSONATION",
                name="loginmethod",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "revocation_reason",
            sa.Enum(
                "LOGOUT",
                "LOGOUT_ALL",
                "PASSWORD_CHANGED",
                "ROTATED",
                "REUSE_DETECTED",
                "ADMIN_REVOKED",
                "ACCOUNT_DISABLED",
                name="sessionrevocationreason",
                native_enum=False,
                length=30,
            ),
            nullable=True,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_user_session_organization_id_organization"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["rotated_to_id"],
            ["user_session.id"],
            name=op.f("fk_user_session_rotated_to_id_user_session"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_user_session_user_id_app_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_session")),
    )
    op.create_index(
        "ix_user_session_active",
        "user_session",
        ["user_id", "expires_at"],
        unique=False,
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.create_index(
        op.f("ix_user_session_created_at"), "user_session", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_user_session_expires_at"), "user_session", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_user_session_organization_id"), "user_session", ["organization_id"], unique=False
    )
    op.create_index(
        op.f("ix_user_session_refresh_token_hash"),
        "user_session",
        ["refresh_token_hash"],
        unique=True,
    )
    op.create_index(op.f("ix_user_session_user_id"), "user_session", ["user_id"], unique=False)
    op.create_table(
        "invitation",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "ACCEPTED",
                "REVOKED",
                "EXPIRED",
                name="invitationstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("invited_by_id", sa.UUID(), nullable=True),
        sa.Column("accepted_by_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["accepted_by_id"],
            ["app_user.id"],
            name=op.f("fk_invitation_accepted_by_id_app_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["invited_by_id"],
            ["app_user.id"],
            name=op.f("fk_invitation_invited_by_id_app_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_invitation_organization_id_organization"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"], ["role.id"], name=op.f("fk_invitation_role_id_role"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invitation")),
    )
    op.create_index(op.f("ix_invitation_created_at"), "invitation", ["created_at"], unique=False)
    op.create_index(op.f("ix_invitation_email"), "invitation", ["email"], unique=False)
    op.create_index(
        op.f("ix_invitation_organization_id"), "invitation", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_invitation_token_hash"), "invitation", ["token_hash"], unique=True)
    op.create_index(
        "uq_invitation_pending_email",
        "invitation",
        ["organization_id", "email"],
        unique=True,
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.create_table(
        "organization_member",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("is_owner", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "SUSPENDED", name="memberstatus", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column(
            "permission_overrides",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("job_title", sa.String(length=120), nullable=True),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("invited_by_id", sa.UUID(), nullable=True),
        sa.Column("last_active_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["invited_by_id"],
            ["app_user.id"],
            name=op.f("fk_organization_member_invited_by_id_app_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_organization_member_organization_id_organization"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["role.id"],
            name=op.f("fk_organization_member_role_id_role"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_organization_member_user_id_app_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organization_member")),
        sa.UniqueConstraint("organization_id", "user_id", name="uq_member_org_user"),
    )
    op.create_index(
        op.f("ix_organization_member_created_at"),
        "organization_member",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_member_organization_id"),
        "organization_member",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_member_role_id"), "organization_member", ["role_id"], unique=False
    )
    op.create_index(
        op.f("ix_organization_member_user_id"), "organization_member", ["user_id"], unique=False
    )
    op.create_index(
        "uq_member_single_owner",
        "organization_member",
        ["organization_id"],
        unique=True,
        postgresql_where=sa.text("is_owner IS TRUE"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_member_single_owner",
        table_name="organization_member",
        postgresql_where=sa.text("is_owner IS TRUE"),
    )
    op.drop_index(op.f("ix_organization_member_user_id"), table_name="organization_member")
    op.drop_index(op.f("ix_organization_member_role_id"), table_name="organization_member")
    op.drop_index(op.f("ix_organization_member_organization_id"), table_name="organization_member")
    op.drop_index(op.f("ix_organization_member_created_at"), table_name="organization_member")
    op.drop_table("organization_member")
    op.drop_index(
        "uq_invitation_pending_email",
        table_name="invitation",
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.drop_index(op.f("ix_invitation_token_hash"), table_name="invitation")
    op.drop_index(op.f("ix_invitation_organization_id"), table_name="invitation")
    op.drop_index(op.f("ix_invitation_email"), table_name="invitation")
    op.drop_index(op.f("ix_invitation_created_at"), table_name="invitation")
    op.drop_table("invitation")
    op.drop_index(op.f("ix_user_session_user_id"), table_name="user_session")
    op.drop_index(op.f("ix_user_session_refresh_token_hash"), table_name="user_session")
    op.drop_index(op.f("ix_user_session_organization_id"), table_name="user_session")
    op.drop_index(op.f("ix_user_session_expires_at"), table_name="user_session")
    op.drop_index(op.f("ix_user_session_created_at"), table_name="user_session")
    op.drop_index(
        "ix_user_session_active",
        table_name="user_session",
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.drop_table("user_session")
    op.drop_index(
        "uq_role_single_default", table_name="role", postgresql_where=sa.text("is_default IS TRUE")
    )
    op.drop_index(op.f("ix_role_organization_id"), table_name="role")
    op.drop_index(op.f("ix_role_created_at"), table_name="role")
    op.drop_table("role")
    op.drop_index(op.f("ix_audit_log_resource_type"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_resource_id"), table_name="audit_log")
    op.drop_index("ix_audit_log_resource", table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_request_id"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_organization_id"), table_name="audit_log")
    op.drop_index("ix_audit_log_org_created", table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_created_at"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_actor_user_id"), table_name="audit_log")
    op.drop_index("ix_audit_log_actor_created", table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_action"), table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index(op.f("ix_organization_slug"), table_name="organization")
    op.drop_index(op.f("ix_organization_gstin"), table_name="organization")
    op.drop_index(op.f("ix_organization_deleted_at"), table_name="organization")
    op.drop_index(op.f("ix_organization_created_at"), table_name="organization")
    op.drop_index(
        "ix_organization_active",
        table_name="organization",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("organization")
    op.drop_index(op.f("ix_app_user_last_organization_id"), table_name="app_user")
    op.drop_index(op.f("ix_app_user_email"), table_name="app_user")
    op.drop_index(op.f("ix_app_user_deleted_at"), table_name="app_user")
    op.drop_index(op.f("ix_app_user_created_at"), table_name="app_user")
    op.drop_index(
        "ix_app_user_active", table_name="app_user", postgresql_where=sa.text("deleted_at IS NULL")
    )
    op.drop_table("app_user")
    # ### end Alembic commands ###
